---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: horizon-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgBcvuh+1XwzEHvqSY4sDmgAxhV5I302hxSD+5fGuDk1EIDh+RFxSri+uy4bUDSi6KGjtZpHF3+Ro3m1q04Tcfl022cFo7ui4czPhSX/wGR75ixktbQyzCWlwYpPtoPavsqZPS0+OT8QAPpLrbNNTs6NzS9bbn6aJNjQQomMX4NOQbH7Q72no3fhQAmV+kGvNmHQY8J9dk4jZbdDgT+5M6JtXuWnCtYET0gMN1WiYz8oPQyCIwRpzBdSYsPrM7ohT8rhvzpt9bsO/4N4ouram0gOTjjVrLBXipA/v2sbExdR5Wq/R8NpvLJWCoNTRhVBZQMQCPg06M9Q/z9Mwk9P9IyY2NzyNuTswJ7n6rzEBSvXZiq3NNgiwsQi1vroe84iD4Fv0vmbhgf5F7xF8GsxeQglyARGgcQLvZtuJMqgUHJMhyDhlTyzNvz6+iNS2fw97msO4xuhglJInDAIy1m/oxFiysg8qHk16HFS5pb5/n55YhRa7iiPKNhjhwAoHTRZhaUUBXIumzT241TAVO6nGa8KzN+ZLUn8xVNZHmQUAcmVY5WnQEB/KV6Ki2qE0JQt+1DZDMTPrgxChnc6aXkF1t96X5tB+4FW5RPX3rBWa3c93Tsz0WfcOTwvVULOH+VmY1nnPmIJq6llOOHDVc2ak9TQ/g6+vGvp3nBLc1ewkcZDMhiREFc6vewYO1wC8qMG8m11SMaKnY671IPMyE4QnMbhdiV3PjUW1aiGymyIncBfGg==
    username: AgDRPvmV8dVfxtxDUooHiHLR7A9C3+1WeYzSRK3V/gqBVQNpjzODMKT0DuaAUnYo/FIS69NTKI1pYx1/Qnfn+B9FIrfL/N3PrdLtuNuRoivakXHYqK1UJhsUwEi0BTdTfdQVanIE8dZre+vdXYEJIUDEKqCnqIOCWFm9SoNXWPQqSH6VOBr+wLMKDiAaZsdzVDy2YRK38RKtb91wT9PgPtCj8a/cB+4UWY0atMfL6qgaVKFh6onL+oQHdxsyPa3QsOm+BI4ot6EjL1OYbVhu4nprqyIUOqnCDoqXjf4TtmhNbzwjqaL9/mjtkmvo0SdJReB1GuoK02oikp7iEiU7DrMKNSNd59vbc29yww80w14SwPvhSwibITz/pkK2QdrfXC/NtY/UcwEyRjv1rJIcsw8+0Z9mn2RGBnRZ/A5q5i3YTYZ59Wl3Z/JtKPefCT2Umwok95BFqQgn/7KewCBHZ8J4CTiB/+s3yZNfjHQZRP9NlmqHTkZTEeks8ymrGJMusZrzOZGs552uzXZ1y9YUNApWqlfVkBwMoI23ZyGBbSMFpecehXYiECEwZfbSb34ZnIVASQ7xpg9lS0tAMKemeWkrsuZjQsiVgkWks2GN0P2dQXLVLd2oxyBRVxahJfwoZsRyNn598H5uJKtnH7v4LnG7rbZN36AJpCaBpaPzTy11l8R8u1mf/NYUt9FV/eyVLakgpKqo3HVN
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: horizon-db-password
      namespace: openstack
    type: Opaque
