---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ironic-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgBFEdmVSxjbCytKOgBFR9O2twJli2khcAmw165L9MuXq6zQbMBUzmv87O638zSMo/8W8pY2MPDkhYldA5//PpGli74ylQ1PQRQYpvwmAc16DVVthBbamK2r6jzkj/cP5jb6WD+U0CTvA3FOYWk53Y2bJ/Q59930ptupR/MaqMFqlP+egBTlhYr2NU60rFHf+BvH4IXNvoJWXjkHbt/HvutA0Nkh7kFKJANHzFkg93iLpdfn8o+9yULGaKmBSXUWQNJFyzpCNZHeWx1hIhn1ge9weq9N4F2d4VLyqWV7xdluvYOhWg1rRswOVDiB00ctJC67CjIZYSXRjBI8Web9yqjMp5j5JjjDb4cdPasBg8azirq3vVylMStjK2RByowBzrLvggxudydqspQlVyRcTvtSFfAkpbi8RJBmQI3mRXsCsjs9PMzxrbri96x+g5O5coQZ7RxuvtdDLAK3e6zcOGMxC5YOXWIxvhAZnzpfHAxLAtJVRd93LyK8dtThJXNi5fLZkHNdeC7UJowpcviv9MNapcOvhUnZeA2WOwU+jgeWO2aLMCo6pJFyGBWZhWA1JiAO88YWQEShB586Lph+Jp/HnjBw+Jy26s400bz6RfBxODFCBLe+++BG+HtMA4a49G1zFxnlDv/vSsUqloLgPxwiCUjMzkNOIVDzHsMC3MBcVUuElyV3/A5uIfViC6DGfuebzKfoUuyf5d5pdK2A5dWam8KC6WzOfgZJX4ky4Oi6AQ==
    username: AgCWPICUL45zMww+OnLvP3Ywb1QqHHYw0jr/jh8440pENqZPMiNvPbT3OrhTIzgzOcjPGgF0+WbcLm6Xq1do6PkBkz9FRl9Ur3djxax6MA3NWu7nR3hZOll1Ay4JfFeJwS+zdQOXKfEvDxGhtFej4cWbN+vSm5q635ZoU9tkljswzvTmXdOeDX/PqjcyqZZZwBt/bsqAxnb7QuIu0o9nnlkt1g04ByOo9bf/j4LYHK0pXDs7/2ve1YT4kG/zQ49digH/AbxP9g4MS8TByKQfK4moERWtVT0Lu/5kmaLhyUMI4RG0ciuNM9hMBHk4ts43ypZiDlZKRb6z21BlXx3lfdMIrL8A7g6RlNv4n1cldZmndo2uq2XtWlJsTaq7d8bGQqB5zq7yCieIN7mR5p+4+tga09qGlp574I0lNuS96VGFj2O6fm442S6dxO1r3LgYOK+KBKjneqmnVhHY1W5wTCcRkx65ClKpoKksXxrj5s9ryT5v/f9NgIV0nxPN8DzFjpMdKQaXD+clM4Fzk1yNPdqUyJkJDiN8vmEhFCIsw7oNYtQy+bujWpi9/GtQEsBlvMno6XEmKr/8hl/VfQ62Tz56CME4NIgzf/5HG7PNK0VnEGSIhixKevTM/3zesbz94F64h5IUOiAUGnqIwTvJfl9izitdT5dlUmyPrdhC1H8izan9VFeVc1W9ObW4thCB03NXAqFH7qA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ironic-db-password
      namespace: openstack
    type: Opaque
