---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ironic-rabbitmq-password
  namespace: openstack
spec:
  encryptedData:
    password: AgAFfFCXqqRBAsraFG18/MKh28LvgQhm+iMh7kHY/zk01kr9JGu+Tj6wotCzi2aB/FhlVJ2BIcxxf6BlzbYFMBiECFiXytEVcP/Zx9UaQcKfsKgpU+BhfVgxmW6H5BlnbZwEIFhF4T2EzrcURXRQE+o+zs2uf0yzS0kyXXH0ySGbwbN9u8ZBGG8Mnph0c+s/GpcLRhi9M8GDoPxSpBK8M+pUegTWKVQIdEyUW/dh/9FE4vhYfn63kjthwvtgE+2d4Z+bZBH49shgvWxrHoDqnl6z5rLW8vPH/4TvGzbzu16vi53rnJgAR7OjUYMTic0HHkzwhdZsva6BPm1rTPdVUMxO1P5K7n++NaxKjdXdwUmom/h8mI5dcIKBZiiSaRlWK+wAbKS2CtgtHO5CiTV26dx33Tck4/MOwskia/rmPcLTDGDRQQJ+RHjNyaloitUttcr3mQnrGUG57r3sf7mw4b9wuRql1K8WBE8LC41scsSBbk5N0f4nxjGdP0RgwWan595VerWeyyx/+mMJUep9DqqM6TEHl7nHLaE2i58CA4yOX8JuPP2ssM/Uz3R/kNlO6G4LymzbzePzpmDB8D6gnPAiGD+gy9DhZfC5VW7Ih2hWeENypwYB2aXv4FSa8d9zhyGO57dsvw5fdQ7hcjbgkDzjyjObyx4Eh3t+HL+hpvlqnmMe61kpxp9liJXLq7ApEzQ9flbIOEFMELgWrAXQNp7LnTqp3JLBJXs52EXpTPEQ1A==
    username: AgALDDFL5w9/vi+8S12RNcuRI6i+RsPBSU4VdWU8B0y2wdFx3a+0aV1aoDAroTSP/daCBxpdsSneaGVJqY+Axmfdzrr6VlHiWCfK333xO2C4of3YFqAWwnFw8MvZTVLAKlF5zAis3arUumz0g72S1sdpBQKkd8fonbaWEuhl7QheqYPSif5Yzm8tzic+AE9vCQIdLdxtDEC1bk0uhyToqrCh9rW6WgAZduqATSvS3SN3tXarpT5rHpzZ1SfVwod1AR0tbZPcb96Nr0Dd/asRLaIUxg1n+zmXWssoHUZNc1HCjGrdZJYxXmytqmwP34weLAPH/q4qimwsGpbQSrvBxwS2gvYvzOtImiHwCZR+EyaxPLJMWN+1odTh0OU/4FIWk33N7ss/tVkWiwWYo2ANpEwczZ0Evvv9BicdqkouF9O2lw7f16dI18az7ufjX99cZiXJlyXKEPJCf0IwavsbtcWdtu9DdhAZ7V+V9vPo4+SpW5GFsKY2jmYeaTf9nhQ/DA2yiUkyWpxWTcLjQyOE4Gf2KT/mK2358LMC5E+CDGKV4NhqzXT2YpFff409bNnl4RuLZhqtP9v/c59pAx8hZCFiPtDS8PTbu5v+bYoX9cE0vbReT0AT1V2ueg3RW2cy8/I2y9z+rRrwjRABvNW8ETaNHwT8wCmgVVT9mkWE5v0L2LMLv33mITd6SQFlwFE3FlwkbABB4Tk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ironic-rabbitmq-password
      namespace: openstack
    type: Opaque
