---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ironic-keystone-password
  namespace: openstack
spec:
  encryptedData:
    password: AgBXCtw6ZNUyu6YLdCmnM0a/Pxrl45Iud11MSoXK2332sndyy468yQiB+ndoVhM7gHwnmRJbRVUM4Cruw1pd7IfuBSCm9zPClDYk4D+gg3uHbV7OtpVn7WVXp4UlHcsAAcSi+2oej3Dj0y1Tr0qPGRR1EQbofXqXk/hBphLN9DHeQNZ340wohT4DCS1Mp4GtFvfSu2QTksv7IAKgL4p+c26oDoqlaUlv8yA7aHGaHmL8OjjnJV1xi7ke5VUEQFys0uTPa554wjMJXQFrJWdKTD0p9Qos2u99qQf/yBou31XFNRz/CVd1Wv2hTM+9UhigY1qWCdlmiisuXrUPrvS7FrHqEIUA+rXn7jqiRvhd5Fd4/aRzZdum0nUu7A4EFes7F1odVjx8Dc5W7bkrRCMqmwOOFpdSkBn7l7UwFWqs7fqTb13+rXDeosBYuQgd5hIgh7CxzzErlg9Gz5oufe3Z1HbW020kZc3c6lFgfKV/AlOnQzElPuUGVOvW/7sYJoyzUFq5GfZ5jsg5Z5FdeKF3TUrs+CKtghCf6gqNwyGYCvfCzUE7vOSzgc/MlHGX6BkhC0DzBRevioN5IGVtz/kxPH/QfBWRD4ttMaaT0nufcYNsDPY5m2Jut7aSdaNchzQVpkD5Yb6COrOWEII2CPHE2MdhD0naZI5psFOmWofjt8q8pZZ/dLMc+uDVfnjIVLtvwwnGANuypFVaFNsy1aVKn+m0J/SiO5bYtUjuHm+Zkigcgw==
    username: AgBtstyopAWbxuN6PMZ/+wyJxngXNsCHukYjIW72GHVE4LpVl/OIV2o5DowPnFUj9OSodJh2i5TC9WaN94em9EzVPhXk7PJ/+9kNBfpFZrwYxXJnuw3kwKlf3cARcWYYwkB/AsChObvKraaITHLaMr8X7k6Bn/wxL0F2KLlFSi3f+wB29MmSfj5ANf2mO8d16oOOR5RKUPHBFxFBEr5G8FhxMJNsXCTHGKov0IFGYiWE1jzxQX9YvTYcctRVfbZ/orFcB59Tg6v6H2fBcFVW/CsDVHePXlfuKEFOUcx2TDUcZF2rMC3orLbpEYJ2BtEIETqsCvNQ7ddmQrgAi0wHzAb9hNsp5wQUKPC50qzgnxCjomQnnRIkq6V+p8PZDjJUFnvBk+92/TQjV2sUdldPpQlVzFHxqVV7LtRUrgHaxjTPl59lS7SJAKFMVuzmc8nyp2lkZLxatPL2V3TOJSbEdLu02qesnwHKl2AsUyRm9gT9OVZqnhNwW0fHIbI9QlFTTxWcutkbcTqOLXpf0UJ2sNo1emqavDUin2jJqdk1V7x8p4C8fxmtC3MkDmHFtRXgBCgxOfRkYHNg9rxrgRm9wk6T4c5Q9BlKaTdesbWCez6PpK3MEJtEVUwRu1TmAT/qtrqy5h7+G17OY7cr3VkBhw/QYmwktGVlp1nTFfJy0mFKyi3jPIN+jRui2Pset6BGbqU7L2l3sGw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ironic-keystone-password
      namespace: openstack
    type: Opaque
