---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: glance-keystone-password
  namespace: openstack
spec:
  encryptedData:
    password: AgB/25GQZfC+Cj4T+pt5yDgWZUz2nU9j7zL7Z/tw1mWBLGhlNK8DamZlVWG34uS0XyBSDvqgO6lAHEP0UhkCIYHt6aHaSGxtSC8ydfyBTUXPpDFIHdOCA44c2pkzqvFgG037NWN/EO1c69auqmsgU7RK27C1YxfhWQuIvI1a8xzcPv22Crrbq1IhU5+AJOD+f25CpqUO0keqDi8ebrU+d3E4jRcfE4qNAuf0CB0YcunM5/sePjyMkQgITLaJ4N63oMKsw1M0mixzT7OqLA+6Weknnjtd3mDoj3hMQU+KtzKyMkgMi2S/XuTlEt4e4Vs4ocPQvCGr9FndckfW3RuVwYxQ+0PqDMv0+9htnST4IE1+qqUE3DMJH/X6TttRXYkyRK5cB3TcsvatVEaibJH5P+yZTeSP/2riSVIFzo/Xtzt4thxDe9UNR0ysCsD1kL2vMMkPapd5Sa3Bx7q3qqXSuYvZxogCXk6PuHMywoKIOCjVL+/3r8Z/cGvS7DSqCmnQF+GVzD5BS7nr3ceKWzB6x3XKmK9UkRoUEej4eB2XMykNAlyxbUxyvZJSOmc9Ojg79WM+fZghCVbqHdlCirMqo72rO+T5wmI50cR/8eqWgIvX9pt8tiN+49v+W93/EWQUH+3G7WwPxfUw8qlcBCsw+5TI6z84Kn5JLIwZxnVwkvfXEjJN/XmBAyTsj0lcyswFwBmLT/vSuHE5ilkaw/A3knwLI0YQ3mgR61RfBnOAlpelIA==
    username: AgCFhiLA33HDqXMoGm056Php9778T3EFzgHT5/m/mnVxGwAT7JpJd87jx9MppFREVFZhRApvFXlrho4/nwTZ46JvOOHjdfBELGd00QGCmVjF6mO8WrBU2uWqBEQcDX70a+AclJOlHj3zb3IdHEj9+8RBKJJABqrsNnvoUUsbTBh4aU/L0mmqje5QVYLiyqyo44y6q78bLdsqfucKb351JvbuxMku7Gh2QeY0wPRRGbNqjUZgPDO9Jka2ezmLWNnf2tN7t1gwXIsAtoykTitNkc7I9oxzmD3JzYI+NSC223VV4G0PTpehA8JK3Q16yGvvB/C5pjoY9D3W28L8T4qYBvMl2JwB/NB9zb3VWMeAtTUEddaL+PKl8U4Vwa3K2UhIvysPiZKOsrChX+7EQBcwY/K2VyYD7j4JEeb6Tsg4dxJoI8sAeLFVuf0UMO9wFBSi6c6pum8efmDyKx4Bkca2esgWxBORxIDUcbtZBpytG9LKpCvA3Rdgt/yfAlYuP8HRcA8/6ce6EdHbTN5X49X8pORvUZz9ibrZFtdkRzt9D6SPcNUPDtBFxS+wEMZlw0eoVmMt7gtty7L9IwheGnf8k5xxcMd6YhIB61MUeK6uFKUW4uSjERWW4+fwWXUdm6FYb5MdnQE7K/rfmoNl8qHGNnlnvXqJPWpyzv0b/IN0qV4KowMmoE7mz4OfOUGeYLdsSSwxZOgc7do=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: glance-keystone-password
      namespace: openstack
    type: Opaque
