---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: glance-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgAIhKLm3WOiFEVYz6vQRrxGeFfpQdMgIPHR1r205fvTsMRDnLqJWb/TF9L6sFR+0FcA3umXnp2lWaSSMYmDfLJbRa5dwrzzqs0vzl/j4IT/kxUkdq8ZfyC5iPxTN/YnhIWrofQ7CJgZFTHrTO2N3of/qZcLak8uzB2QF9ZbiJmigZeLlWNBYIcoV2BufyEmOUZew4cUk6teiPNbCcSVUj9iKKaLpgxma/067sfNBY16xr5AyZ5CueDfo0tcsT6M07jTtRfPc+XLWwPlpLfRoRMgORulRGHrnut/SzAvANM7YbVUWJBeWDQmo2gRefFjTMN39vxNBSFUByPnjqXdg2PXupKkGA+X5TefI7Xf2DvSw894H2NiYWIsGHoxMilRxAaG4uJv8/EEaxeBxqpDfIsPMPSDp/ZbdrQgKXFF0PO9HsGiuSik4Gx9bbPTm19LZ8sCrXcOEQ28yG5LK0YOH7qspSODvA3NLsi1+Q2+utrFkFCC2NTtmnf1WIz71/teUV4xs1xDD9cBFS4qLSegWWNJfML42DG5IzmTeT2Gqxuan3G1hqijROxYpUL5MKkvV8/YEhwqb9Nqy9G0MDaXNUgnX67UmJZyvIqUH0GLeQrN9ED0JIbuzrF04QYgF4ccbHciFMiB+iNjfRtS1Os2KT6D5ddVnQBMGs01IpOjT7pZQHaiC5mNbP4qgT01r/NIjSZuyIMY+YdUC6wYjUrROgmWOUVcEp3n2lhtSmABN+HzwA==
    username: AgCtElQWFA1qAsg7l4nhTp5mVYO6XF4ZDluEQ5NnU6TJiekywCeDYp7r/9PhaupO9q5c9WHUhFMLvdygDhb3o1ENBoaWN1TEKDogzwSebbFsl+5OQAbm5faanopY7nBUdhW5IPb+8t0Fo0ojPVl2YhItflSCxSykzG/9gc1RcQvFihWFrAqqTNW3ZcjVuJfzzbpUcd9KVCPy5eNAZ5Zu7lNwes1rCUBTlFlobw3XTt75U8J6jyO3T0yjvv4WS82VvrqJgqogOyG+lzpijB+uZO7cTkJETJuI6nEf2rWgKxqAXHHnDodmA/9rAso2boJidMShFglhM51Ezz0PSlghKg4+uziPI6cQ70VHs7/3iqXSvzkuCvxC0RyhmBibKtTIJmR5p0nLC9m9M54BRhaFHb1Ljj3dI3/C79eVqLjTQqM4hFG/dpyGwHmInoj8LVvhu14OFGXH2NgKZcHdb2Ns40Rejiqc/y273uA52Fk9lmvDgYQ8dAf7MbHnAn6Ad6my4zH6FG6dMLlcLD8KqXGY4tMtkkhp5w2ZM0UnD4jgM19g61e508PO1Xj+eiQjtk5dPhmOmt+VQcrSq7Ul0i7zcaH7FiuuNQritdukB5ZGY1Aco9oBCI3QgiZDTW8ysLqMwmpifFaSd4kJathnobsv1OZoMU/7mfeiY0iwUe/u9pq4LsmNmbOYRO6Itr3jOGXF7t668Hska8o=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: glance-db-password
      namespace: openstack
    type: Opaque
