---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: glance-rabbitmq-password
  namespace: openstack
spec:
  encryptedData:
    password: AgCK3mavq9de8mvWHzk5UV9GQ+Z2b046Wz26QEnyc9pjX6qkJVk2dxZoI1ClR7TL1iR6ulEPxO3Wq1Dbo+exFcKVeA7AOeEj5fj4RsF4FTTJa7P0MH3JP7AgPArA4zxpjyLiJXVxZRU8gUgf2RJISPI4suOqrXEUAS80sTCxbVXuq2wzRhPuht2RFujGyQj/f/f4evOr6PoMNffSzwNwGbmAfUyAbk4l8z38cvzD0t7uaUNFEXuWqxJv0ALGeusmyhHDifRqrsjmROS1FGCn/qlxTgDI5vFQON2t1sSs9PtdUO2WMKim4GYDKsmkogOOl0cka7TurI27hXZl92DLEcW6eWmVXDLnFh9gjwEdJDWdkayAypWsslJB44KQXlBbNT336MTef8xEsz7M8eo53Rt1qQbn+CvBNOlgozVG5ipJxZUIJ+L8Y57LB2OnF0Ok04P7bSKIvVFCwox4TResumXRU7h/odeT2RGO6Rb6k6rQFYnykFhgVLvZGKuRPZ76vX54FQ10uL+gsAFcNhfzPuK6SMyhGqzL6BMIRcBD9QFEVTslvBihWjl7ioRjoCAipfgQwSCTwvFJpgTN4sJdhW+gtcF6aXIMnTvcFF/AfkrukAhOFhSIB8bRfEujOMttdYA1KEWvcBdb8GKPvss4ns2ec8K3akmcxJ3SYE6scGPcQFF65eMt3vcwqaVS4PCcPNs3wyBr0jE+WLmZkXudmJmMUothI6xrA1OT8ineLSI1/w==
    username: AgCAQtMJ/iFadXdON6J8VEdnm3tsTTAgNdsB47P5cA3zej3WPkKsFgPAtFccxyn93m0WOjz0qR4S8jmeqJLfZzUjBDYkzOfJu/63r6jFOxu7rm8RloMac/yMW725f6yUMnQ5FbQt4fc7XYS/eYmDxjWpFd6FgTNIo7Hfm0JyBRr6dbQ27z/gIPZpm0vwAP5j/GDlom1bXoXNaVuoxwXYvG5c+n4XzXjeB51ar7mCxuD8UV8g90wZyK2wBeTY5EZycbPhlHGwYUi56vgjKfMQzcrEYICwX6aLAcvGLSZmleIP3Gpvyn2Yrm7lW02aURVtqLHhqE3bk/+GS3oOhaK/8CixeVfMxJPTIDjAwehOQwsETif1B1ufvZH8Lw9fCEInseSrlIpWScAnm3rA4lM9vwtcRrb81YZW7JwQRmhhyxwdvq5NjSguBnfTKrHlr3Fa/Wt+IXxp7bsqJr1tw0TPwCzQh3oetziiKYsarLjywpPydfn6SzOJuQMe7EcdKl2ZQiNDR/HfNcVxmfY9FzHAYDij5k+UF2HVbYJmDfCWWL2W0rp4KrmFpeZC9JOjSLT4YlBmtozdK6WLEIcPgKtA8oVYpScuuXrsMFwxC0jxkaSxIhGRZ5Jil3VZw+xKqZuv2O4ySHQhQt+GeVpgb41Dv3rf1IrokZPERtvhs7LOpLe98gxPwHyiLTncdGdq2r9y9o2oRpBc/mw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: glance-rabbitmq-password
      namespace: openstack
    type: Opaque
