---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: placement-keystone-password
  namespace: openstack
spec:
  encryptedData:
    password: AgAxbYW4cD7qDnQyY2xA1oxYTo9r0q6J25cjjq37KLI2/t5DS++PxGjmd1do/F5nknx3sw657MjgsTOsmVLXaNxNAH+qZn0HiS87c10jzjbmy1RourQBD+/6Gqg1yYlYKSWqy8a9co1FHH6IW11xzgmgNdHNz62y7+t1lArYC6UG25vUJrjMguFrSVJrsrScYkNAAPi7jiqRzCp7Pcf6+3CsNpal9Ygb/Kon6OGdRGdiRxkKXt6fdbkeplQK2FWTys3+AMRkzdA1yB7e2ofSgwBM9z2JCim5p8dry/K8RFoaVCkzEpNrONlABBawr+ycH6bGAARoT+MtOmorQr6YoMJ/WbKQezdDeuV3p/V8Tm8cRfcFq5VbAUGdwu9JbCisijyx5ipKuKdTbB3Zc0u/V5DpoluugpoSOMq/E3XJH6CPZwRmM4QHmZRiyX8/FvNDHT5vv5QWiL2iJY1H3uq5Zx0pV27W9T6kW5EhkxwLT4klTgKadJNGQfR6ZamSCRViMx8v2DMp9TOKGZzJAfoZHt1wWR9Os3fFPNJHy6GeF2DxTsPmFxJWU6/ZyXEvit4ER7PgjbFE16rnDP2PJy1DMr9E4g9tQvMHY9dyPYB3izVe0LdVSqrsK16QRVfcpL1Td1MA2+9I0iKZI0euanRY8aU/PT55T/BSz15BQpnswAj2jyAWrHv6GyfQWP6U/VhrQPzS5N3Dql90yTDjJfTqkQTHzjjnoGl0rAC4dhj4ClhdCw==
    username: AgAFzJUyJgggWzFceFkDgJDlkfA8eXU5KzCyLVOLqaq7Ncxp9CQcjKlvsa5OWviWKIYp1wqkcw/w9Iyvo+8HAM/lSb2E4MamWli8iFaw+G9zZLFYGav4Q4oPu4grCKvGYBQ44AK2EKN0I1MBEYH6sRxDneOYBp8cIbY1pL+z5Z2CBL9TKsdrTl6Z+BOxPoN5J85WwCkV+DeBsdqGzows8ymLfp8SfR9tZrDPBJEqAhSpUm6yBao4E54XL1qdo36dVyQBA+CzgRwQ15PhUP1E7SicFsN1OQ7r4eDHLxebNneyHBtmVJy3+2DsZ1OKnNBw5aki86DetTc2gLNoIcSE3zSlP7x7n7RcdFK2XfvJs5pE1CvfZGicBhEtft62PJ0Hg0VEYk6tC+MIm0+QkDI0agYG5ktbnzGpSt3TjSrFbMsAoB4eM+pgmsA0txW8rihik2llfQEX0+SnjNtadwuHOjh73kxs/SKbvPqeM8ECk9MLjOuDL//49CuK6AY0LkB4lu2DVuRjGq5o2k+KwMxxZcIy+IjCff85GVe7suKj1yH7AZT/KudpNZsFLCo/ToPYT8Oc5LAC69C+q6LNjxFvdEbs+7X1st7bAro7tzUoBcJIlmniwGW+8m49U5icu4ZOARi+yZdcOgvIJ47tG41j5BfMvG/olpFbh4M9cuhXvKrBPftuSWmZU/r93N2y+UXd9mJOUZpoQMkdJfA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: placement-keystone-password
      namespace: openstack
    type: Opaque
