---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: placement-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgAEsHv9SXW1iCO+S3Tq5PJCQJZSEiR2cnulf3UKRqUqO2IMEweK7cGz1ZRMnRl4dK0sgaMEuI3kwSrWqALfNy9E702lm6k6CjuK6lZUVZ0E7A0QRWMm5beRhWAmq/nNCqlMGU8PFdrdeLKNcR4LChz/n595HLjcjJZ4PCtPKyfg5VmzdJ3G82Up1a+wCwzfs2eFo+KQxA+J+aktdR/8PjtROa0BNqSifKWOTFiVYf0IePrnZkk+anANlz5S62SZvnE+r7y3jVSvPVNc4orY6wn0o+V1ks2oLJNssW+wVMCpGocB/4wCCqMpxdgfghMguoO5xUkozoCo9d4EPacLSkB5pbPEzA9wmWB2p7AipYN//OYqm+H4yip1MCg382jcJDJxT2GBOY9fpr3qMbzSnQe+4m01DD9p+xHlJSV0i5oz17EkuBFxQ2jex/mBYntYL+AwBt8IPuItP2tMrhsPqqV4PeadAEvNqpnPPiG9lc1uvVj2wmGVB3yb76pA+NX5nib146/MU3sDOLFRv8Iu3DA9P0hZmir95BZeRA/T5KKffAfqgZ1PCRzrfc3WvYZHREZj6HTF3yx1/FiygwJhglhO+yUb+y/wpm4Il/OrOSoVse7Jmyw/iPhOeFRPwe3b0zIw+VbUh6kGmBZDxiSV4k4W8Uhuc5iXa56fgk/9VzGCgSnpTk/g8+ZMwqxqlilUMCXRUoUFEJdY7mqf+0Ra/y6RzLe0XPNot+sM6s2JNFEFRA==
    username: AgBvrZfPyXlwLszMqNpOo0+U4uE9skrU0fU/qS4NB0+3sK9GOm/OilBHzI5SESqykITSV9F6sji+DkMGQIMxM1A+mtf3/YWE7C8v7ljXZcRto1q7my7QvfgmeU3z++mTpAykQ89PzskHe09ee8sKqTwyfu2VGHuV6DvD047mpauP+HsJz0a9JKhGHeJiqgTLXWFg58gPaCPgz33t3HhUsHCIN9zKR1Kdyn2eY8GM+ox35i5pEbzZ7yd34Pld57/fNDtH53BnKT8IY6xGtvOmam7Wn4/cNRNreVHgyTIg3dRb+eVak4Atmoc3OYws2n/HjW/36LeGrok8O1QM0+tl9cmL3BY7t6QAaYs1qaoddTJ3tDZmt9BJwBZkIgu08WRSmU5USML3NAq5qzzLQegDi6giS0M2mkQnlwf8J5iao+bQpqZ6mMhxY+lDnaAHbePowObmqYvkNg9G8rv+SCuZS0OM/0HEOXNcENYATHOBxjHDI/3uKUKt+/TNktjRU7woDwluVmOoyvj+0+1J/bG/sUl1AnUauDgyKLvg2ADuSMZ0L3abioSTdF2noIqcOBa++cCO56QXwhtzjsStoD8pJ+V3O+md1Y3X/Aj5WU2qqdWbNKMZciH474LNP3a55v5Oroe3RLrC1xNP2GO85m74HL25miC2/OHug1u13CEMt6DibskklO2o7GS8tHioTsXZXj8h73/FmwAfZVw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: placement-db-password
      namespace: openstack
    type: Opaque
