---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: placement-rabbitmq-password
  namespace: openstack
spec:
  encryptedData:
    password: AgAkOXtpoOsZtGP+e2tJMrnz7U/cGf5tvhSO0CsvG0etxm3L67kNmzhcqAt0VvD3H3sF8hUePlYMVugL7pXnmy8lNhxkRJGy/FDB+TfmDDLpW4O0K4TkTOs18ntU7ro4FANO40PlY61be1KVuu08nqT51HPnd97Vh6meRA5o1ME2B3C17bUewTEGoiwDkCATJ2wcXQNqiUrnuEixjDYAUoXwPJYrOaE0qrAiaXeUW03aDWcY03Sc/+7VEaSlzV55e6t3kdgxOTXhB/zAZ28vGsVtxXjKPpDTnXStDzyLRaZwh23MTSbCTMH6dTw6txtdp/JFdRDFQbFTOitrFuplmRyB2SZsXIBqko4obXKqvzrwWcd4NLShOJeQa56lqKTpdUHkXECY4cKuEYvS+2XGTzyf94SU2eeAFCJP9XiG3OHNlanTFDVcPZUnaOEFESXMLURCKMIeJJ4FDLplGnAEdcJzgqnCvalhwWFCH0FDTc6YjtwSJD9Fofv+qSAq7S9FU5Jlz6oWpO6mvSFhN8jq8KMmtyCU9DqXyhWUnaYnHQ/0H9/iT+Ssuut77/XJ+ouZLxppyTlZ+F54jndcAoW5oaL7EGf/k2u287YNs8Fg8eyAGPer4sryueGZGQyvLQPbq8ofPQ9zi/yAbT+sxvpiXT/D4nhEeaY5+R6/r3djYy2Aw29Kweg3JoQOspuequuvcE5Jajo8JXNHJ5hsOfy+hfYyr4cTICiJhPE6taqZkQGm/g==
    username: AgAltyyytOLGbpgGm4FdFyU4qRkswqjt3h4agnIj9YzjbQKv6wlnhD4hLWBuyZr5jN9nmjlspIFCF+hkSIssWveCsJv+ZOUu8ov66d4gjdndIRc9TiJVWgrhFReoYhvzsKE4TW9kEokbT5FO5NKnRJ+JvHb2Xb+inJsi/Fnc7mVvFwjLUKxwu9dytfCAZb4nt1sLRKi/QHMZAO1VuVLWUNR1un33NtcEDwqtEvPvSaIBXvBLegbd0WbGVklMV5Heec4j19jnqWm2q+ak0PBsK/CwQ+0ye2/wAn/vQYuEO0UrTmXtgYbytjg4h6k8R+9vUs19UKTWCAlpQOgqDdGsJ59Gm47dcyy//zYVdSvemD9MXNNFZjiFXT0MRtHbjTZF8riWZdo8hf8X7HahQDpstES8xwKM2Hu/sObehLsRFLLM/uAmvKYM5siMgSyfY+H8e0JB1vnhH02IdHbVQ2qq1BrLwM284p0f/TOYpLzoB36JDqiyG6Ttnr8n8H24SMP4hLF2Ls0FgqvdEXKBZ7Hft+maU8QECTp7YwnSM2UxkNA40AItQdmNMHqc6p8J8m83eI2I9V5BeGJf5qV+z/txapTN9+Pcq5WxZwiR0ZPtakSaOw57xfj9xi6v3Xd1eLWsfqUovDOvicrKt93PFdHEi+aHF8KEleP07ruJzC1dY9qVllMFEYOzAAxGxwKYHH+WAhzt7A1IOQRpmeM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: placement-rabbitmq-password
      namespace: openstack
    type: Opaque
