---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: neutron-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgCCCsJdHyNZWEMXETn0f+n50w7S7ZL3xnhWZhfuWCxQeOfsE1yGwKWYh2oe3pnz/TpUt9dfM9jnt4m+5EeIkdrQSDJW53S7Tf4hM6UxCns3fBPv+FVXPVoXbThpLLHPMGwRjxcA8Pa/pplSg9ZweDwNiYJs8gqyzQPQW6dSq35HrBzUwPADBM+83t1AxBp74+nSj3ksWyPClVu6fSDkiWYHGHTjAr5fsSHnkVt3ihvobQ6rTMB1UJCIM+M11xHjdcseRfmqRu2XJrvOgGsZ9mlfEW2feq/3hJMIPyq6sXvZML6Hp6OfX9tpY4A4MOfcPrmooY/xTM3fv1UTTccgsxjro7LcPmGM6Ehb1hRSYan6rx7lsCVNanom8VgD4v2zQdcL7S95UTg0gn3kmaa00FsTd6JsBVRqMp77X9N/5po7poNrIYvvVIutWLdQ7sgoP4/P3zgHmwH4OkVIBcljxWk78hOpBRK24n4aMhbGtuGZhZXCBEk8i7ryQU60xSolzol6yA0w/mz0mN8WKhWpFlvRw3au872pB7P/8IksTKo0QcmjyN9OUCqMEd82wk6USIZ1mS96U2S6rLbSER8pvwCsLocWdKEMp/Azm0xN0g/qzCIAYGzMdWnFRKChpnlE6Q0mn7N0/9hUvYDY1B/NcpzsL0XhoS8lIe9nXGpMzAdpLfOXMO6Uf6ouKeGtKCrnsg7Em4UJIVFkj2D1TOikt+5ok55ZWvA/UqCrgxXguT4z/w==
    username: AgAz4L28QQWBjecbIinFhuRz5Q8aumkEBQ9VNFn8GO96PjZop0aRB0zr+/pSkEdTxz7mZmnj5aeq5f0OjGYLaOCL8Bs5qxIo4DhJRwMEy8WeABPAxd9Cr+Vgr69uBXFq00TduHCnGOT29bzU44MEdU+KS0U+kxoLrmuOlRMB8B9cFYrmBvisdvnNced1sOO/FMjZBwloCdSeMbQR4ePnC8nQiaVDyFr67ueX46MaNVF7L4W+UJ5AqCvMMQ+OT6lRfnoyiKb4fq0tF9jLQ4FMcOYoboTUbWXaCRPCh+73Zc8CxwFbGoon2vmV48eWmHnDB7EGeTZUamq8jQNgc3atmGWY1nVkMUjSOfKNjYWr5Nw522j4s8x6nHYJ3fSRbQHE1sr7zPL7HA3uzKWyjQp1bbZL2bNXGcxTUKfH7KVhoZASx/idomTFwWkWymcwZFzJY2PG6yewwFDAotEUcOPLAfKDRTj+uCHd3ljMa+Rnm2C3BOJdOBtcMj9EdeOeE3jA0zS4J8jJunivsCbVnr8ejvTi8dzqQhQfvWyI9SLWAf1KJmMHebMkRbG9ueIiv1z/8jJ2gKK7Jp76eKIBJZlMx5TMSla16pMzA5BSkJA4JWMHtK6GPLUo6xeUvmKkq9ypep0k/EHF7FWXP6fda2ceG3PmdteB1ktoiUrAoaWaGzlqYK0Hua/rBgGnLppJ5DLTEa64TNtd6M8t
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: neutron-db-password
      namespace: openstack
    type: Opaque
