---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: neutron-keystone-password
  namespace: openstack
spec:
  encryptedData:
    password: AgBJCgqhtHVN0d9F8M3DH37HmmJwPMyxZrbVFCgjUZ0wg70SqRPBNu4haMp1GeLHgfxVgNwpB7yslm+nSNPYrs873xwsEelReV0jlczW9SvioMWpnZdMEmdDAX+VQO0zTVK/Ue74aycp/n4qrchP5aFOONZ/iB6panoXfyC7hdTP9qK4HWye70q30p+KhnW51z5oTr5ZExXfpqHFhTQVCWIIHMAviZg7JFKrFw1ITaPoYEs4I8aQBXfK2IVqMb0DGNuI1E2L3w1WY7qf34FLir61uRaqWnD9Bjh6pWcOE8MabaA/7lezbEg+DHzVRNA/D4TJ0DDapICtmG+B8h5W8QJxBWowtcqxxY8FybO58KUW+gA61H0xeB1TAo+nmCMZ8SjPhuxusaKw6oIP7BBAPA4xAShpWRpnarlIGrLj8jvrp5cSNuaHFmo46rZ6F7svjpaf9YV4y/PnpkOjGk2gGnoAiQ0lqmFF+eIg5UpHZS59WnvO/ZQet66BqgGPtwvW3Yh+AZ0g125voFmXKYDlD0URgdQ83k7ux9sNY40WpWXRy7N6GHQScjMrJSr287vt3yZ7BTNWKLoJkYT9HN50iB7NwpWgcf46Q+McY+p9ZfLrHqUYV3HSMYxG4kpNO7vl15wVvdN08M0bWw6xDjWNTI3QPM8+XrBz+g4mW3dn/a96762rsRPlMsW8l19uixlyAt9Q1Gjx3RhVxHocddko91PP3JyAAb+kn8l1U+SV34envQ==
    username: AgAwQggwm95kr+9J9iwffUliVLbOahRsAg9XzxLhBOMeOGpnH/hL0JSfoIwf3l5f6z4aqJqVYAbssvIddp2aYM700AYgB5rr4AbrdWJmpgl8pVrzeU1iBSFt4vf1z+f4fkTxB3MtAT8urWfVCOpL5g1yWsA+2p0S3yrfqCt00unlsRsnJC9Qr//i9Vc0LmNV0/9yZRFH8xPhrnGNAiHTDcYOPvrE9e4bj/ETLQRnZmtRnOpwi9K0bUT3vZCFzOJm0dzvsWEm7gLtdIJbILctaUzkLZggyQpk6vqjYz2EBnFjx1o6AdppmnQ8h27eFLYNeI/8B5gcGHC/of8xVeWb9pbdLbqC3Tq7x1tdBvp9oPD/3TSJ5t4BUC7HdmvU11UGneGgzw6ZrzCvZRfJ4thmjhu/gX2FXT/HnE9un6egWX1Aw938XqluFdKzO/K5s0SSAOQt5NKoLzOmlZtiG6mbbFpcoCNicEmDGDgk82ghWC2Lp/JkxyIc7xUs5mxBsUQp9DXCiMcBYJ4JCZ1kSjUtitb3nLYvg4nb6Hs+oq6vIOWb8T9EZXg56DhsKCiB/N9eXZZ/EAJ1NOzIYQlrMu7yqlgv11AN9tWtQBUsMIPxfshDzqSktWdYNr2g/VbjToHVd51RDjc6+EW5qCRals2wT3xGL/sobU19vAr/jdxBWK7yuD8fziweffbAm6d6wfO6CO8xQoL8Ae1Y
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: neutron-keystone-password
      namespace: openstack
    type: Opaque
