---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: neutron-rabbitmq-password
  namespace: openstack
spec:
  encryptedData:
    password: AgCIa7Qb3CrCD4ZhsrI8kI0wdiFVWnZ+dLGdJ+cAcKIWOoU3ZT77mLjzVmufFdn1/VR35HxwrUZCA0synHa6qrvVfcwhxP2UnQyA3VEVeRju6+CI/HfMWc1tSBwN1IEgFBYEg3rSn2ITLL6KYb7bZNaadshrXWxlkShBXZixbPYKapRbu9B9F+R6hPHptc85j3X+sVtqOIxDyNMavVDJqTrSGMBG34BcH+wzw9/v5uZXFiOM/nfPQtSW9+iJ+GRBp4amjVT6X3yCkSg2uA4XBcMGP2jpDHQBUoLjLwx2OEnn1rg0aRG8bS7V6iW1wNCUtSGVxCo/jRUkSp0tEJPw4+DU44QGaUcYWMv8W5miYL6v67XT9zQFZtEj3wfKKwkqazmAb98HSkA+qv+nqJr+sx6fDcJRtnwAE+w0xokNQkKLaTTRODvwfRV1fEBoHA4EinzPN92cyZkUWZq4CrdIT88XgTlIFiPl3JhgIKwJjHv3KEUgkmcUq+XiRhCTAO+8AO2DayN1Rseb2qonURza0dV9V+bQwLHNRiDaJaW/Nak17aVq/jgHLD1x5G3Ya+ZSbtF1Pwwm1jNDLZkRfB+XTHTkB6NJZzOGcAO1/33I7VL/1l/7miWE+YB9Vv14ApoM1WiCvk1VwWI2VMaIZbT3/oNek30PKsGXABeBHLQJLZAbt+qww6TaujtKRMtekjS4T3v646XRrxXmjTP838vKLQSdeYXrghdydtc00JifHV6l3w==
    username: AgAHMz10g3NOgqQiimSTkcihNsnQs+spk/mUnZHb6tHLgp440SPU1/TeSTAwX3C+7STOjzfZKGM2L4INVjZSgz32CEJoy4Ubn5I+ga7w8RtFQftmypoSU3QgJtjBCOXLYuUAZ8ZqGlE1h0XUjPLvi/sLyyqDAvgSsO/FSB72XO37Lc7XC7a9LIhSxV60VlP9PjHS1yHv7w5ye/z28HkG0vF/4a1T7/rtGFMT22eiXKmuYeTKy0xXTD2DjNFJiwlfkz/LyTycqls65PfkjiFXKlREeAZ/v3hH5pHqqZTbpt/ENzDPZBbo7IYy0+uBn/RqF0dctE9971CdDgcS2c0vbMcHaSEO/dAZqNENoXCv+vYY9ccsit5ToPoENAMIt/FuEMrYNd3RkaRvGuD5pZ7FYg2Crt5vUPLzBgbZYnkhabi4vGir5n+39Uj9MdkLdpGiIf32jbSeKOBjja9hIhtTlCUTQZymIczRVrpLWoEnFMzXFhFKf1ZWxWNyl3rKZElwM+h6sMNv4CWLR09xWTzDl8abeTGGAlkz5KQbzxAyUf000DzZCRQom/oeBdFWIxBV1Am+Fwl7Bgp5qvnjc9/JhUDJ9A1zy+oX8ApZle2x54Osx/y8JVSlWpsMCcrKvFZbrF4rLozw4f77WtykbCtCLIpDB/oMrDtFYiFBCHW162nzlB4PmGMIe2jFBnJuY8ROj4Kxzp4M8SfK
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: neutron-rabbitmq-password
      namespace: openstack
    type: Opaque
