---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: nova-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgBZ1vsoKuOZc0ErwZLUFAGJqAnaET1E8Sx6iwxmMmQ9pwBqNWf2UTqWK03HY5j/U/UWANKkH/NZ+yi8Akau5oIvFWQOhtpPV7gPaxhZddi99eWa4/pTNK0qHupDu6P7vHM9W/q87WCi78RifDf9fCpqtjrzee+cJdemMKZB71sM/Wrax0hN0fCWaxdUqDXrQbILWa0qwKrceVmGC68RzEGLjbDPbB2ZzebKDuonUc6fUnLIesV5JhZSZ5k3uyiqOjNtie37DhLjZ5Mzjfz3QtQauM1CAxmF64JPlxo8NnZqmBxaPN4CcLmPuqy7GjF4FBYWnVzj/zk6Ig4dKs+6SHYXBGycFSWK0txWd+3yfcLj7RLsxM+aRzszxYtdrx0Xzb4C/5ad4emGnXmwtyrr/lR+cZ3SWyN4NTAARoXVvvH3PnjyOaJ55tjnN+Xr0iECKK1on+QV3YkM5f1YGEZ8txqipg/oTCvHoweeZLSVRC1bY3d3zd0zA1OPP2iC9a8S9VAHh7gWHfBSbsT0hFHyCrHr3yzT/6ZmcYdd5tXse6+RhMRXN48DPtzwWbD/CqpPx5c0DM92WnyjZb2GkMT0nqZ/otKPyUq8o5lUGeFuWK8440PyLW8hpC8NHN7k5J4ifjkQ5YL1YMcoEteQvBhX4CTb0410SALbKiXpISte9Z2O2Fr12mdFVC+egk6lcRhDAR7rM+OuXz7oD/KdEDnyVlZok2ptZ0IJ039BCHalPgdmyw==
    username: AgA2O5Fn9w2BYJxuUucBbuI7PcLMMvOj/7S9MDoZRgIAIe2DIKssNOHt2SWBk+y/f2JbAak2dVM5l2LLtTnBpykfv4QyEC+Z8hNgSt9eVJhqtqO6EwfsId3Bj8UCeRVt5S2uE+0AbG3cUoQr0on3TAU7CMOAsSzPToouJT7X2O4HPujKAPvhz2iv7jgaGWsuAL+4boFoch73sxee1n+5RD0wrNBdRn0setnA29an6kqengT0kOb8/4vt2Bo7LKFWSXt+ZtrvIF/V2fJExog1oP+m0BDzHAE/hiw5dmthM/NE4H5cEbyYGOhkqcQZWlXs+MVlGqiWh5C+EkNQL6GE+SifGUVMjYPMSz56b4FhSORGXwGfOCpJLkIXrgPk0oSwR38Av6r0pogAXgCkscuf0kDoyqTxoXHnfnbBiOJSXOUNG+wd08aTpIcAdZ9nMRy/Cx9NRX+tDL0S1z6mliNMMFqfUqoNXHi8Q3hFKxzgT4UBWCY+n57+Ae1bxMfEtJNkKHVkizrGuEHobmcwws2iMR3mcGk4wJCGnlLbdRf6aKFBOIUVq/fJY4noexndijqSy8v6XzaR8tFs9H8JUBNeNw9ZSj5waCbvMXt40yIknqxG2dC4w08nV8WOo27XSql3KmvWLjv+3JJFV6kcrpm9cgvrKu5FKPrdksjJ/6vs9/aOEOqEO/aMh8VlgTVw7fD+B9DSz28X
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: nova-db-password
      namespace: openstack
    type: Opaque
