---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: nova-rabbitmq-password
  namespace: openstack
spec:
  encryptedData:
    password: AgBk0hoDsK1MnRMUWKNmCZlsG3OrC8gWAiXLvGtuaE/dvrpzDMFR1qwm8ANHzYeugyYL+7PKcfgp6A2bwSxTfS67oCec0MvHvzHAsfR73t7fjnzsQQKNHvradpSNt8f/PVVZq38sxYkHIZ4sZxzW60zBQMwXk7e4RzQgIZiZuLx1Z4NyqMhL1VQ8OtIC3b6fOjv3ydXlD4ninFIekqGJcH90Nq0oVLs6/nERscagCXxsMpCTAlObbfCoN0iB3MzbPoRwuxiM1xx3T8c52CwJTWSfRHEP4+tf7K6gLYPu5TSc0Mrt67U0pJeRnVi8Z2PnITMC51LZ7IaPKTB/YgGwGDOQqIrjrd+dVqWKu6qI4bps5eLA5/1tqB0ah7H15+3b5NY6RzHJl8WG+OI0rZigKQPVXPvj45oj6XVooTy3QvwFUJsK2ftR94wmF+I4lNYLxc/qzfOCkL9cngmjDo10NKS7VO9ZjdxjtSqdtpVHJSewsncwfrCY8OXucqgpaHn6CIsMaGRRm9lxaZA0RQ2Y1S4gIPOiRTEM+E7f4WhxbcnjpHjVfo4BY3nX5F7aMR2q3d27p1lL8oRQBePYDR5LYn9VyIfLS6DtJgOYBE3EeOQPV3QV0DI5jINm/RqE2x2kK8IGCIAmZ+mK504ku1KxAX5vZbLkB/5F0l+fIf8nqh1xV4uiDMCWhtTcPnFqxGLwyDr7XfK+z4dw//X68aWr64HLMhgwvLkif3GgcHUHu/SvPg==
    username: AgDGH66AjuuqWVrNSfBsDs7IAz5mt/ZdUIlKsE3iZ2PvsKrEo/2PM+kljAp4gBpV7m1Nt6sKYFIHSr+3BdbiBMuPydrS3ubaKjwsKxBt6hcvtwT8mdlzmzYsyXpz2eaLt+On73t76fUYYxJYAiuhNjB7EouMx7oRgGJMRRCOR7y1XFrgRGA9FevZ+fqgoUPgd1FeUgUKxm+C4eImPyH0cUJ0O0r5YnUUy5UqZ86k+NNVfWUYhrD9w9rv+Bz8SYJo4/NsQAyKXkKpzH5LcDjH6N3F4VOvVB3FA/ATnFJ8PHZQytABJl9GAYuQrM49dMiywY3xmeE8uiP+7xxPRLpGx8rJE/EQcDTq1EZ3edUl7r6vNkfrbFp7q16nabV0sP0KSc8xNvwAuAi+JCrALCXqJINEIgKnk5JUBysmrnTCMLgAyPWhEfCi9H0/798gQnJIucRBK9JxKM3XRVMMWlRrtAiULEDVk9M69q8QwlfhJPHVp6Bn4kKoMWLVzIWdJBSaBHIO/AMF3f+TzFm8QT/utaSI89rvautkfYRdiYXNCZqDKzNK91nYn7oQvruqQxIqSpbkOqYsw6nHZH/yyleKrWOOOdq3255JhVtP9M3lQRz9xG+f4JkMDCnW8t+FTyfc+VX5D6e9udsr3q6MgOPPJ/mH6eKB8i7in8+xQZjJ+QciFiuLgESnMpdMwUHBW2qw+MzG66RC
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: nova-rabbitmq-password
      namespace: openstack
    type: Opaque
