---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: nova-keystone-password
  namespace: openstack
spec:
  encryptedData:
    password: AgCDxBrXQk2IT7WlcvpeR2KYXuukZ88UifJw4f+xpP4DJP28Wiq2kjgw2MqA5QtUNGYwGRrMxtUtENCJyAOoLSYRoNDyRxAnW+IsbeDa3n0YNqLbuRJIqeqnlPyKqH/6ny+5TS4+ygMQHsAc67JF/Jftpght3PBO7zVG2EDmjS2u4aMNidaUsWozK+/ecIMnu2fa7KyZ8xCkkoZg82mPNquartphmDltTBn3HadVcbv+5O9vgr9nyus/BFFzsWe+hbwz8hNfm2GqmfzbOY1fa7iDaPlpD/UE46cD1taeuJb/KEjVmk2W9ORShjQm9ChcyDLPtKC9lrQyUZbHezrseO93+UEXxFpYFb6g1T1UvQ/86O4RVA0o4I6rlkrbKIdmESA1z01KD2krZIy9Vq3tMGGKkC51r27TZ/F9ZplUH0tD8fFdmRMvzGFRe71OKAtilz8FslR6Rh114g6SfKJtaAfE87cWu+r/I/UWC38n7mJn0ClD0qMhcdTkhXLY36MJsrZlaOgQtb39iZuM4QA/kj0hekn9M1DaCd1Fnx4u6fhcc7OHHGnEzBzojKis4HtK5/QNcKvh2UVqVuD/0eHeeGUOtxqCEyi8siL1h30dLcdWKKTOIr8wu7JYLjp2pykGFck0uzA01l6Ae7bQGZhL/m7PcT6eWv0OjVXDV0oeMRerwTxlJkithA0TGQ0js2h4RSMgXuYvw430w2Jza+XxTN3fGfs5fw0dEU+879VS4Kffmw==
    username: AgCSX8+9xjhF336OBsKwtr5Pd/AtAJsZeG4C7Xpwqd4zbCJmULav7/FGtCaMl3spGQKMHhVsKSQ29KbhQmKnpC3Px9Sd4ak0d5szxhjxBabMr6mTf4tOrWrx3szNQqpSCAR6X/UGu5yXtYFqg6gXnbshFs3MrcsM8zZj1el/D3rSkcp9MKq9eBiFePIOAZM3A/5PHDCrH7XX+ateSNdJAW8Wp6oIOgJhkqYOOYsijmSkAMY8454RI4Cct9U90iqdQ2Glzre5GZyrfov0qWxuCyFKFkn0lTRUeJEsph8CKB8Bv5j+nCj9pVNakvK7O/tjboWJ+//HXJF5ZkiOHMQHIfVAoZsYoy/ctIFtwBBJ0yWEDfu1dPRRyDGOosfH01c1RYKOq9uAhrw5tlaYdqpUAagzpaovnzJTcWXip1XYnlIz0hBkPP3Ey3KiwVK+DVj7sa6Vl4e0VtrA6Grsjk/rbHhsTaCo9ZfKwhfC0fNR3z+CUGAGkqPeA0/fY22GkRxI538mPfbqYUW0WzxutKEDrMFQ/8W30jjDJZ89Oe3Sr2pn4FcMUIDnb8ubMacSwmYnYszKx8cEJ1am5JAawFrmX7sGKtIqG2XmFfwdOl+mJt/uvI5qGk+WvAdVZUhC+LdTev8cFu+RdjJM7Euisrr1mZ5G7l0f++fZuIyCksPwOQYgQ2lrXZiMFQeMAptZdjhMLFPtCcSg
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: nova-keystone-password
      namespace: openstack
    type: Opaque
