apiVersion: v1
kind: Secret
data:
  config: eyJ0bHNDbGllbnRDb25maWciOnsiaW5zZWN1cmUiOmZhbHNlfX0=
  name: bXktazNz
  server: aHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3Zj
metadata:
  name: my-k3s-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    understack.rackspace.com/argocd: enabled
  annotations:
    uc_repo_git_url: "https://github.com/rackerlabs/understack.git"
    uc_repo_ref: "HEAD"
    uc_deploy_git_url: "git@github.com:esmacancs/uc-deploy.git"
    uc_deploy_ref: "HEAD"
    dns_zone: "home.lab"
