---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cinder-rabbitmq-password
  namespace: openstack
spec:
  encryptedData:
    password: AgALBdbmVzTTydKLaTDvNLDtRlYAijXr/NhQgb13Ra76zSXZBfvNQ8Mm6p73EXiNy6LMJu8bDE7UxkgPqzow5hK0S+f612aZy2nCTdOzylPhfnH/4pEYBw2YZA9q49Zv0IFpaaeGJkybVnakTj5LwpwLbOm0E/Rwvd3jsCesLUYfhYSZ68qTeP1t/QAzyMsZ9Xw8HyU0/OgE5zjbI/0bGgHo0S0I53nDBVrt3OBSDjjde+359rvvhaHg7KgPNA8wDTAMzFs4We9xd7BdktEXlxwE5ETAENVWPNyCtlOFtt5j4t2d2KHjnSCCkXJreuCowqh9eHlXB+cKUvOTLFL0zBgmnrZ/BMhd+HQUGsMAfPdIOfHuRuqc6q5U0mvN4MAVcG5lVZLn2/rrP3i92CFlwrAnYm44w4LIi4r1wzxxvb4iC946Itvr5qKyAgOB0s+QqyWtd/o6C/laYS2bDqPR9Y19VkCpvfMe4PXuTrZolA6qpjKbewU49Hf2v2B15R6Y9IwRA/VevCuvLCStJSlbxysjC0rmp2R2vFSpI1sR3sN6BcK2pq/aFCNBrd7zzeMP1q6tUwVgV2lBFQbZcyrhLR/y3rRIDMMfvPMbhAwGMdhFD52u3msyeCTN5RhMhMgybPCwB2qauiajLRHao//Cdpsr1fRjXoFZUnviZyXDRnDlIy12TxGcMQLSypin9itTSf8PoeZlp0ueenFB2PtscGSJa6InyisRxJfmkZA3eraBzw==
    username: AgDI+pRc7cuBJdIetfVd1rGYMj4WHF69h/8W60Y5yl5VgP+osyUkiv9SvMG3pUhGJn6mPlGvkZJ/QfMGGC3ES3lDGRLmee7i7SFmyuPXT1L0WMBfK9QhVHAcE73rGiTQmCVoN7tOVnS2ok/qlXAkY662zzk//RUZ8ZswIz9udiCHvMGfEvpjKS2k6lpQ6SGdob/uH/bArYbzZN8Eqe8PIX7v1m8DAX3PoSYF6auucV+OI2/uDS0jVjF0k8D8k68nZtlfJF5Oo/dzCURKDDN2fjQ6BMAoH+SJX7xwb69G1M/GDjMTJjMdcijlxvsQ/KEPjVzy+3BOhkVKbzm2n3KItqZleuTSJkkZDURJAMq+G20OJbmrT9KsGaHO00Dgw8RsIa9xXKLGtK7svmp/nowuxrDyQeNUNRd2KDFnzRf3SZO6UuOy3JAo1terKDymNrMMnBUKsw1IKfSPKOE0XLFPVScChCfjCpGIL0Ml2QXWo/S6cGZw6IizwDLKRjChCEnxinRvrPQY6uVcDrTnqEPu2LHCWfEpajolF6fQYzP+ao6StPaTjGiXhlmTJ0dD8ScEnbKKr+AzhV8eigp4KDu/Z9vz8hVreJ9Ke3CbX3F8dIxV2PY4xSEVxbxRy7thFR6HSRS9XRJ6Djsi6shhhPcTurBgeGh9O8gTCdduI6XfsS0G5S2liUWh2W2K429ZmcTer4Eocp1j7OU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cinder-rabbitmq-password
      namespace: openstack
    type: Opaque
