---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cinder-keystone-password
  namespace: openstack
spec:
  encryptedData:
    password: AgDIHOh3EqEw7cQC0xwYxmrrQezGdvFsaSa+JsKZfgx/L9v8QzUnpSbL6LP5SPkv4I5fJ8E9AbHIQtJHzRarkbVrl0hmZpdOuSk1RdqpAHGA7oZYZTZac6j+L7r5YQUoMkh+bagBwrmbHLxxT9nDjPCZnTKzyER/gL4wVnuruRX7kABKMYgr+O/zoMMKU5a+FFzzU6rsfMqEJSGQDNn+BxTxjteYWRvzfnsGveEbPhEimb9X5kIAKN+mMU5vCfOOJYaHX+k/eNrCT85IlsEqTqXDlLfwf6JE6H0mAiRFgU/OlmrXb+pLWq8ix9nE+MGs7YxWHvH4ajEa0a3LK4TSKYOqs+a9k0Hoynu+PUjMH3V4iTrcX+mqdVpqPHiqGe4jVkFkV6JUC3+YWRN3jdEOcGVmtMQ8sSBIsRNyWkw6LzGkGPEiaOZK4+gySDDRt0lUQ+49FWf+guXdma6J0eJqjAN9TZ6gCRdedImfTYlfok8+HdXIHBZ9PO8i3p02W17vJ4oPZyX6Qy8exC/+Vn5hVSS0Yms6BYnv4cEKupKwBxYvgfLZpVpu9SYV2GA0PEYjUnomkbz4KJfAuuSLIProE/UCXy4Q4zpUzW88K0KEwiS8YdBxY4jAX9jpcqN4EhCQ5LNCMTmGW5CG1N9Y/BvcA83Gu09mNqvh75285l9ktS08jE1f5O09+k4ByNQMPgtAWgnRPZmlTscsco4CdPDD8Yb3kuZqgrB5sTc4qcG1fu/r8g==
    username: AgBq1b8ECirpSpYrRXssQSqO+iTg96T7HenTyUss6Z3AALGzeAQHNQ8kI5gBcJ0vJjDE4hxCFAkbyqJSlvpTpwiMH+u6pRyOuVXby+YHbtGwaZeqfv5qxtUHmBlP7kdKZwGHj1weYeI37z2dKxa0iUeOqavagKRAzML3CzJEm4gKYalT5CEnlQSLJ9dAH0wK8REjkptroNCGsPHbcrydX5xrokiEwIwGmqGkS7tDsBfKR0AgrwoxOHsqea9hnz0ycoavP1GoIIOHjo8uFgM4zcmJdpkIMT2+XdWNC71W/6bTyZZzZ27WjMkj8QbGWXd3IQHZQukECzq02mbbcZLzTs6ncuZfqfF0IL9dTCokZgzy99mgQ0m38tCaA3WcdKS6W6X4OL9E58eYLgiHn8SBEP4NB23HmbCAIqhbaIsSO1q/6zlIrw7Yfu/erxvdAktUwTh4o03fTTXKleIh7kO5nhHlBaOVsRtw6vI/rkOgqtpbFqfj1Ad3WdvCQvhtqFr0UpG9bpvp9ZWpTO3ByKHu4gfIpUOeI+I198dmfjVzaKS97aY5EhDJ5wD16an5dDWmeNS74Ykp2CmsQUE3xxseQ3U/DjQ6u8L+blZK4VZvPwBj6DwNPz0BiLcb1g5jD5KzKQ+l8XCxI5cV+Jmp4DHSHjSOedeaecdsXyGi+njuc3ltvufhGk6E+luKyVtgGlnpNDJ7iK9vuPk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cinder-keystone-password
      namespace: openstack
    type: Opaque
