---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cinder-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgDKA85FQ9H7e8p+qe/E8enotgwuFl+qr0x39ZSCdADZMbXdDY6AWehwq3Xg88l6Ln6oYGUrcg0U13fGlOCoeu6qt+TkV6pn47iSkNFIPu9AxCM0WmOnYT1Gn8fGCmbMirN5lyoFDzDwIE8axX1RmZbLnBgwrfL9peHNaXGKCBIolA8n2v3O/Iv9F9CsqimrEHwhETTe/kV+QF7yjhy1m5XaxzOAcUWGujdt6eNao79cAoTzPikXdyDdMn58iCxBoe2x0KHXhu2Z2nGSUNz4Q3cuI6dAVf5o9jOeXNQ702LmfRhJ+MqNqpi4buxdtgKIgwB7I/1e9+R4qdauy1hkF0QDY019OKeHkVydVIh77H5NNTrjGYM0PK/VFF+HzSGF00zMN178NZXZe9KAOYrHJ2KRFks0LGNO6HgAJHJlRFr2fW9Tn94PyXN0APnS2c9yMSOV87O/KRSkiBrWwdEPtpIDytuFac/QIZO1rwwEqnJy48AG0G8nSvkxJFi14O0cpmCkl8JUN3drJDSe8XYYnI75Ve0x6qMlxJfli5LEdvcliEHyplOVVraRFcJrqooPKI4YpD+XrZmGOFzyCdC2fVh3pMteACIfI+OkH86BCVJTVuGZt3RS3f04nmphojb0uQTrt4C1+WOeBxsFRGPL7n7LE70xVJ+dZiCdGamktGlhThYRBaQtZ0az5mVwJbTp1pcbIny7qv3YSCixVXstVA7PBDc5aAuBMtWdhQrbXsGZpw==
    username: AgApxVrqz/16hk2pN6oa7vWIv2S2MEAw+zPkPCtJGX1tdur5Zqfr/1dN7SUKo2NPtReXgybBbWvT629Psg4idVl0JvVeillyq4fBvG/IBRJhBpB5ERXKzDOy27BQZHYNOO3cdG3IZe64J3idWugrTet3EHPWlrxE+S7ffFHk4IHIYe3Q7GOkrP9YFyTpY1wTWFpsKoyXweaaxyNCrngx91AY9vdaD82kWXVsLqrs83mkggAtsJqnq+2EKsx5A15Wx0hRwWXEgJtNaje137XVyGOd10yepATMW9IYWFj77QM8/qOREybm38d3VhbLP7ZJQx5BPmhVZlFBQhVNz/ocv10Ih419Ba8sTDh55u4zxpGNnhzNoM9eO4XMnfbtOwocBzPau/YNXGoei2XwQo2OZV6ZUcFDlSwLd2U1BQ3IVrH0iv42j80AQogpNhu0aChFoILhDQM3oAl+NeCJMIpSMpCFuDinFayOVdgINYxj6TANVbUYk1xC8gUghYah2mQuZUsYLzN+4oCnMLVAljs6L6vYql5YfBYBoASx4MtOGdz7+TNqqJJsgCm7xLwKJxO7KlR4uppBxRsfg8A1pkBWfioUMZkz0+OqDbo7EVJu+M5Hr1NWaFv4R6UzyvAwKKzQwYSZT41lgl/+BpuU9Yvq2ELrZcqWnhJ46NpJhj2C/CBjaJ7rC87EDDBhsREcOthxs8M6u/bITPQ=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cinder-db-password
      namespace: openstack
    type: Opaque
