---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: octavia-keystone-password
  namespace: openstack
spec:
  encryptedData:
    password: AgClGic6BPQwGujV2VM+FrYHP8zaAVrtZdYx1NsufzRMfaQuFiMnTeroBCdxOWBYjjmlV4sXQYf/moK8h8Lsr7su+lmh0uI6A3FcOm5vc8+EtZPV7wCssmEeRrPV3KA6kWkfwQHEhpw0cM065drjMTUNwRlJ3x/Vh/EjRNqUoZeyRBz29TLv2PK7RjmY6pCwyOulEd38zrJBnsn2FWcXfIEB83KH0nxUNLP95zyg2iyNEwYDVBzLFAm1hmoNkbD2mZjWM1T55CmHH1j+8HkBcIi1A2QvqVNpyMUtpJELZ4iW8aGmE80+e4JePQOUaBD7RB8ACnY2h1w7o6dHSlLgUkU4YfYw5QuDMSKKHyB89PdSCMHuAtobBFShInkPIhmPX+kmaHosYs8OzfuvHif8X1r9+mpdIlTOozQMI4xRClAvXkNBqhg3lq3+BhVHe4BCngJB/39JXoz5Axvv281ury+TRb9SXGGLl680gwS0m12ZzugR5nhGkJcZXbV3y8sh8n17ylcp47JooNfFlqnXVnD8j4ZY4EcoUnH20iem+HO5F5JHVU9Leb33hv5jE90DDUVdq+07oFfv20omR0y17zq0JlaU/MCyhhyB2vT7IW2SjSDLB92HNZWBKJ10cHY8zWJOwdYvPw2BpTCaKqD5sSUDZiRw1Oq91cADLVucnTGMUCsPmNXN6E+Bhp8+NwDEd8sR/yk/PnTyz8Gz7s8aI8UCGBc6UvHnbE5y7ofSmWzqoQ==
    username: AgCVkm9IW2nCMi8EOozg5NsitpKCqiOu3PuM5XD3KiQGzh+7vsu8VGSSpeAIR/C6F9kJmO/U3jUPf25wuxPsbKTAoYJOP+MiS/a60IW3rVpfowskd+JoC9Ue10dHnbshMOZ6vgn6noU6MpTF4zJrbcudHbEjP6lxx0K7Xyr4KcwRwPOn1p7zxossybWEGM2H4si0QwnRwvOGe0vQAKCgkuQjuo2jLS9yTzicgYBxoZutCPgenv74lsj07e8/+iBGzpmHgUnvwvEo6ISH1tEffdpDKjmNGb4x8owb+jML3r7obyzef+atE19hul1lhiOm4nqrUlShppuQaeCZgzypg8lZMTTMMleoPD45m5JDltegBLqMjpCs5sWhJ92l4tnS/jQx3NLHZ8qhQgxjipfTaUYb+S6gQTFlxzBluHgijUu2LC8L9vdObxhTsxpUJGrGMqnlleltXsbD4+GN9B1J6C54vPpQia0C2oaDdY4CUaXnrtE/2S1zn+gtnyfL33QVYJ0fRjJFmH66OFQ7Nj70/Iig7eBzSkQAhLwA9PA15bk7BA/fGYQrWjqeJOvgB7iEuPHQ/e4iA7bBAkO+1efKGznno3cJmfgmgMgcUCSKmAEU2ikmFB7gTYFuXLvcLvFTCb5SUH7YS3TPZ/KMx+i220U9Qk8C8/7KilE/HnIm1KMg2CQM7+mIwT2K3rtj+mOo0Zi/jieBgaPC
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: octavia-keystone-password
      namespace: openstack
    type: Opaque
