---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: octavia-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgAlL2UQ8nhIe0Pjd0IdRvte0txquMnEtKZoZF93zYR9+zlxzDSXUM65kgCLfIt3ZS/vucUAtmq5bMSMjn0RUOEppXdamIj4rw/CaP/IzJNkopKGE0x1YH3hRWYMqYCFVPeaEi7e5Q/I0M/YOF6MOBE33bKihtav4SeEMPR4NZA31XVCf7b2Qk8AUurhh6cvvbZTz5TnoZWWkXRLf34jI9YEVckk+VrSSQ5V6avlN9pVF0p4F9VPvLR3j8LQZHWH2tJewBjC2SR3cYIuAOZFezWSGUEW6Zat0Ay60H4XI6IKm/F0iTfU/rU2OFAPcIwXsQbAu3eGaDPWM2yhtczyr2yNgdYOk+PGrUwwiVL46GwjBFPSpITmq81+PNx7H8aDi6uUQ+MMHW+6O+hlLOZSjxfSyuSGN65s2vXv/dtZ33OZh+CNaXqbIiZR/FtBj9pdX1IipkGN43G6js9CR4Ai9JhIM17p8INqzI5d5sPZapq657DIwEd94F781jsjEDi0xEAhEFcMGbEs8n8bEafVhppWAcJx9M2v9LronIRbgPymb1jZZ4MSPHfeHHOXoDY6B2RQx0uPVDhNby6sy7Kv6Y20bkGu1B5ffx3VIsuwq9prGIr8Y8eHX7QeQONvjlO85ZqNnPfb7pfcrftRiMggPJAB+18JTg0JU0VVHXMHOg9BBGMbcR/4NK0Q4MQOe4POS6jT+UYIbGfV6Lz39XhhvwA212gYsvG/1KeEkuy1K3t6AQ==
    username: AgCAnfjkFo7MjiTzleco6mxVaL8KiNkdcnADgFF5Zx9Z+brohOxF9gTtzZyAReWaEtlPn1ksVHgsGiMl8QnkL2/LY8XlKd1LMzlL3c6oPBdBU5wWq9dOmHCijfBgVkarv1I+dAXi1OKIiRWBTyHbGC2GRKRoYViiuUkQLUhEFNlcg37BBDopzP1vEihxxuPGOQb+57pKNrKnXRy84L68VMyUYw67+aIlur3K3MrUPmzPfhTaXZc7j3b/4OoSr4BO1bklbJ1KcMPw1CUzcBxvugY8HugcjskdtFX17Qm0zIQKPLtjE78HOdtVO7fDOPuMo7AweTjPYnE4L4hGA6lT4M/ldw6UBgyC1whqRSmnUy/29nr/AKXVAix8aOzD2WBA0hVIIRavdatTpeOsJN+KESR7bCid7Qb6gTLm4OiZANApIhE+l3KzViQB60pTT2h//ZRRGqWZbAo0b5iHlkxqMTzte6q9gins0q10oeOq6sao6mder7uQmgiAH4ACIRJ/+nWC7MrQKuTL7GwKkHp7Kexnd5+qkk+gNkEPCDn7PYNQ06Eec2yPSctQpJVyR1IwC5cB6ZOu8wrLSDUaMZHCQhTJsCCkIwyLsnxxGmalJa3TBk2E2fPeHfS6+hwJx+R3SsPB5JVp5Gpm+hJWPA0+dlslsap9YCSnLXg9kIb50mFekG33MbtHk+k5XKti1Ew1lYq9A0iU3yYZ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: octavia-db-password
      namespace: openstack
    type: Opaque
