---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: octavia-rabbitmq-password
  namespace: openstack
spec:
  encryptedData:
    password: AgAeRvYqdj2Y9+0bKHsjz4+78FA5ASZdK9s70R8VLAz/lCWU8hYCU9Kk2X3Z1a4yjMiBKvdjK5rlwwG9R9iIXnWf7Zo7Zn9wuYHhS3iwlsPMIVfg6C1O1H1lJhNb+88ySeEm7FJlUFVM525+ouA9BCRYdUcSCLsJTpB66zGney8H8qcw2GWoVA/POFDGKC6OHWdHKofWehEaPPnTCxTXUu7aUpVICqZnfyQjI11bg+cJJl2CzOq+lRZpp45J9XzyYONaoYVsDjF/RlQ4ma/bUVWc2S2WSRLGdZI0u5n5et1/gBGRdBEXjKpxiCmRqnceqV7UR7d/uR2uBqaC1e08I/PDD8Az9teZZ39NsFlIYCkqlSBsCPuDnhSAj43XC8rEqgFuKi9t+BZdcbwcgIeM0sA9XOAFmcWUM0S2onXBD663ao2o5YQ4SkTgNK0IpOm8zxKqB6297+me5dXMbOEb+pNmq9D7rKjLeXDBsP3RzpAPuFBIUNk1IdifXoqAIonk9HGW1S1zQo+Mn4wZBkU8e1JTlxxpExnOYU6JX9SdtrNbPOkQgYpM3DHQHo2/5RTTXoNN7l0gjuSqBmD/sufq++fZXkg7AhSbqlXon1GKUewhigNIM1lfepI287c1Fc4NATSZqRhKXV09EGX2zynH7J6MLSoEn8puLfrUd4A0RhEka6c+RXqg+VBWy0UoRKl7fdketZWY3rqEnZzqNlLPHzRXzAkq0mFI1O5eV6MsEBtQJg==
    username: AgBA5YwMNJwaYSka8fGwzqdiw1gRmH6Iz2fr8wP3CcgT1sVGHFt1KMwGlO82DUZQ+Ncl8dU5NCoFBujLotm1aRhu3e5KBCE9nvFNjJK3qi0ayRF17EbKMeIpNq77WlBNmGX3IeXzEYTofnRkh1JT/XaBd+p+fcq6zMus5b3YKIcOXtu8TUHQPJaw24u0IVSE/GoAcpPldobHDfrcz4g9y5ysynmLIbpYjnkLZsd0cu5Y+OnrEnpvjhIRTUfng2cc5cZSBmAmIznH65zfg3s1BDoaNIuzBYuNqzByiEEdJaVWFyqj7FObgtl8KNLrv0O0a9Eh5dKxWW/EqUVcRHslGhH1kI1A97nwg4SID4TaF/QhbpgcoltwCvzDrTzjJ4ntY/mHCUsi3ig1UWHVBEXzgU8TbHtlySu60uDcXA7jwtsSMJFS27kNscWShUYkKBEEr1sQewGqhGngTweek74jhnjTcAcGGPi0Q200D4NbouplQ27B4bUUsdKMPm20QUhuTJec7CeqLQmCEnBdEF3Zw2vI6B8JKpvlXJZRMcz2Xw0+Mlcqnj7y9VC8qdyMhb0RB6qWRRAgITs/20R20W0faDCb2YA5DcUPs1WfAoCC4c3MCLWr5buRL3/WQQHtSG/1QF3Co8QQDDFIlVVr74EbadS/cjE8paFz+Ev9NV+nDCxBp3VRIvniz3dOkNie+jPOG6CCMZ9KV5tO
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: octavia-rabbitmq-password
      namespace: openstack
    type: Opaque
