apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret-argo-sso-dex.yaml
- secret-argocd-sso-dex.yaml
- secret-grafana-sso-dex.yaml
- secret-keystone-sso-dex.yaml
- secret-nautobot-sso-dex.yaml
