---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: argo-sso
  namespace: dex
spec:
  encryptedData:
    client-id: AgDFg7NclCyvzpZnlwgnLliv0puyzYX24oIORtiKbdEPgxAVlATQnKhgwdtAu0E2Jc9sXnB8cn9WmEKPTqZtWdHN64SavT8cg1qhS4M6C7yzOddcKSwCc8oNcge0QW3rIVR1bmm4rqrQTPkekRObPxYMb34F96bdWKvYOqBTUIxqDCg19nSbnZwrcpMezq6HSSjyzy36VrJzArOXRclS8kFaUbpcGEIfoUSihUaMDWJk+UiFhendHYy4gs+2O1PsG9oguMFBBAl7cEJpIfor7c4sCWIQnBoJzzE4ZCvmvqR97wkZDW+58Nov9MbzsWtKnY8n1KHRj8svL1HfcjSolepwblSCUI7tLp5VS4C8Q2zKNyBcCXo0S5Ymv3qSkR2HaGaXyzUrzJ5MaY2obdRGBEUHZxTnxSuil/xfHoFpd9rMu4Ppe6fUwZfnX/jgGx26YP8l+hiO5X+Iybp37PqvpJkSJWMJNeuc6QzSHey9PwxWWWQPML8KmjR4gC1pWN2ibkwqT+6I6m/eght8ovt4lv8VWbCKaPBgQoWglb8vBR7QIlvDwoyaTcH7zkGRZjpajD1mKdLLLXaw21x9hO8iKIvEBimDpBFS5aYfQYxLVD8fn1vWUYwULQWun7wVUx+m8ncdpbuCVObZpsIaL4QhNxLhUzAYfzKdx4smr8bIBxSBg41dZaiACqWw3DcoXJrEG2I8u6Pu
    client-secret: AgCEd83VzsMMwVtyiOLuT+dk7OF+K8UkmP5WK6dIf8m0SWbKUU5HITh6ZV6WwzwVLb3sH3BE5IjOpsYxnE4Ia4ibxMmbKEsoYk+yvkzBVUOFT51F5thYYjoUTu0GOdRZjPkEYGOnb04HbFLThnGeJB5Z5vlQ3qG0ZisXtuouUbLSI08UyR10+uXjPsjnklDxstwNYQ/95luniyFN09eK64P8cTr7TeO4qt1kXGSTVtQz/ELtqq/Y5cXBFD5oZfnrGJcVXCnlrSaz8RK5+1KFFlkfB43sOq4Okf/axqtag/etTtKCVadH28J8UgLleDYQKzm5IUHJRXicIQCVxKw2tAtSJMQZmNsA5yOBMtPMsOL8qbhcuxbhzeczwEtrsAJdwBuJnpfELFFA9Tcbd/EBl9fu+rLe59/rhDJo8liK2AfVOpxRBFytvBA7ztjo/XawfA1GdJKsHat0nKjBdpMqOGWXueVEaO++//aXb5WDVlg496O5MXX5pYL7uu+PEw9l05gQu3P7Ap199i6JAfsgpfaJLNhXDLSGT6npFUveBn3qsXdAzVcO7fh8bYKaVneCv4G7KQkw2sli29Qo3eLK4Ooaj2fA8uVBTnH8Fhh7WlwhAhmct+aFGmFTkzTpXz1HX3paLUOUTmrNlId/lUY9GWnwTxVvzDxiEJiGgYoJL1PhaxZZi1qenRltNagE1zCtKalSr8CdorRIb7Mi3dJxlcSoz09p/JaOKiS0l3reKWhKkg==
    issuer: AgAzIZ0hKkDSivYzi2u+LRaeZ9POXo1ahsQb5ZN25cN0BBB4HSKVhmtuEIqP3RFhUo2QtbGxR9VYptp+0K179dgG+ajJxcdkD169TsVL1RsAQ4M72MZL4B7seQw3/R1wL4C2gKOrxqf8rBHuxVOoBfyomkFIJa4Ax62aujEJiX5Gg2kg/u5H0nNUn4vtr4DebAP6yBCr81VT6Qnjly3o1DF2aBty6LCa9bkSaY/cq2n9VDYpm/kUxpgZr8esGnTZ9f45N2sBVBntxJ+KU9hsQx/iJBW6JrUxG09kjiz3PWAVEr5OWs2+eklKZeYiscs8/PC5mVmaklrgAu6m1C+y8giqeWm7HHwNw7VBI0ErGhXcmly2ZVtRGsuCwExqeA0Wo2DGKBR0ESVYXiLnJ7BrRYOpUnRtqs56IMFPey4d+lDYBkdKLiqQimyBobWZLLTzuf64TNT5awRQHSOg3JM+2vXpeZgU4Ag0pM6PVjbbRMPg+axd4JnojVuGhFBnQH1zG3juKG5zvoCz/5wruSr8bt+OX91/jKncyIoxrv3AdGEGkHioQuQq0X7MR3kIsUeZpZib2jge5IXhfyLDNVe99Z85JxPrF+6h601sPbJ1cf5HUtASnx6ELyBsOpHKllb1XyGmiroklYOO2fSkQId1yS346YzCiBs+TZCfKHksiThNRyNQhb76uB4Uk9AQMh6JDo0VPzvQAPMrRnl4ooHRa8imWvFMWg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: argo-sso
      namespace: dex
    type: Opaque
