---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-sso
  namespace: dex
spec:
  encryptedData:
    client-id: AgAapZycVkDo7KWLMUbdYSHegQuWfCfXsj1EOKWyWXLzdJx9M+amA/2bl6E5ON7LOHtXYpD6hTqs3i2OhftuwmAk3Ech1crj1FvZHHg8ckIy9u43bHGyqwAYdgNls847wqB09MOJoAAeBK8BsrjQRnGMFj1hOP2+M8BnxHIo8A9/5Rpw59zx7dGq+zIOCJkcUlk+2fxa6t9C11jg+4W32UpETYtiM0WUMurKbNJneBN733+7W/NREH2MCq9AaYzk5loKB5KSwQl3cxCrMsRnpqgqgK6rAz2bUXE4An8Vy7cpqpZHz0qIc05nBCsdDQ0QiCAyNIPptetSVNJyIpLQbmGHJAm/3JrsN/fXXQo68OmJXnzYHgksAxuWuZRsDxLWTSPPny9fPq059srcGYLo59E4ZOvUxgigazORkRmkI4IEwZYDSmlE842vvy6x9B6nkgp4SllvSv9kFmL+HUsL6+9y9RQd732orgFL2/0yf0dS1INQFXGt0V6/LThff7R4VES7kB4JOVpMyBpTIfuELu8QTlG0USJc1QJ8mHPJDbx9yefzTCnBLQPrFSUj+w57bKovAPtPt+JVkWiv5VGFQxxyjB347H7lJMe8uSf1W9lq5w25JuDrJS+RxIFCqETaczZWUrDQdwQMVW2nCBYUpAZPljaObsUhiqT+loBKFSupiASD+M/w2bdXmCXHmfLvmkF3H0/ie2oLQw==
    client-secret: AgBe/A4cRPhgFQSshRi0W8u0M3mUOJiXx986hIPsUX9dnWceNwt20fBsXPz888UXq4pbyvgaDF7SHaZ0GEdvjWdjArCfjRTk+w5TQeXTxzaS+LxCPo4NrGhVPs1vWlZSCxS5uYDG7ppIPjR26fHmbQVBme1vRwkBTO0s+PrSpNGNG1j2waNUvEdZbs2u0pip+V+LqBKcKO/3960HhUzLP1L1SJy8bjB1u3Ng9pBTcFsYVo4Sp/bqbCixXJOAqE3oQ7O8WLP70vHQQ5GPxoGAuXEbL/C7ySMIZoe1h90NZKY/4kADyEPXxC+8FchjmlbBZwO2dNFU/ytLJi5Ux8Y2POXBXH8R2aqlEmKfdcLTiK2bp1o2zCc8FptotuW1aIDPRAesa830EfmhjiShb5FUBcQjV7xqQNM8QL/ObbWMe/g8bGbsb3aCcKnRWBGk3YobTB5O5w1q5PKzer7rdoxC8+wchBiz2OclAZu+b7PxWT4LZ7zSiIw3VAOh4UixVWjpaioNHMMsAd3ZkfT+a7rQyytYDHsS5pE3XQiN5S0F32eCh+6lDuWhKZdqd214QzAij0FCl0FlT2iXrpPWPl0k2RwZI3tJP38gwVD3PnemQtdX/5DH7b0pMc0bd+yZytRKRYorhUSqxGcOX/9UzHf3WevhCX/a9M0JzE8ZNGxVap2oE1rczeS5XcBXXp0AgP5rvC3O2VO7JW3ImAAyQBXXZ2TighX3YiuP7ruQlskmjx1VNA==
    issuer: AgCpxAuR1rHZvMl+HwMQdpX8s4KZhHmn0va4R56jZ7JEzQXgybbSsUa/HjFb4Qvikkt4eICZYXH6vEPuidyQ+PujW5+MlIBVYNHE4ME85QjtCBXz7P+2D2SBk3ECNDcZy5LguLtb5JDgRBW4nRi7b5XZMHym/wov/p74rA/iP87yoLwdmDtqFHhLNIbZrqDBtKqMy7CNB2q5SOd3ThowRuEBRau772/waAa7nTawD15wcM02hmF9jhq4JVpBa/5UhkLfOjjrueOI1aWBkjijy7WcRK6gGbRMsiQm4QyHKINDYXE2KxnPn/QT4KC9cjoai389YjsPc59od6QnKfb5WHatdneuokGByWw4bPx/J5SnDwh83bMDZQP5IZh1zR8HfcxTZDKqlFtdC3/F5n4daSnWboJMW9ai2TxnwwGaj9he3ZFvMFtoMSRj8x5sciakgkAVoptl0/4nqdnHJNr+yxX0dgfC37GtquDDF+5bMC7WZs8nCSUl2dabbB0Zd668AKMpOk4yfYqCGYN8vmCyOZ3TMgeq9ebbwYCqttxUfJJqHymjMNwFEva9zY2syBI/HsqUIQ2RSoq8EsruYjjlNcqXSQNFuWCzv8uxz+eS0qW5ppmBho+9d+5NNXeBSYyAAy8IaGDa5m4lm/5zCsvAx3D44YI1YEJ6x0UwSS3raQ3kQwXuYpJlz1QZA1eNRm92VTJjlU1m/YeTYa9TDVqUXoh3hUKj0g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-sso
      namespace: dex
    type: Opaque
