---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana-sso
  namespace: dex
spec:
  encryptedData:
    client-id: AgDA8e/HjQes7E8kC8WHW+uGQzqMTapfmEcn2M4hJU2AZtvSof5Jfq3pOg716lIzMWAjWtgA38lB7rfbHMUDb7knaMHXyWtcD/+dYsfyVDBYFUbzy+9F38HL6s/mml1bIYwElKK+voas8Wkcwfqma2d7ZGA9ZFpFsvy1DJYKnIL7hH+GDGLd9nbes188iipY3TXm+Vb3JywOasyahN9A5xyD0zV0GUWXETFatfhZcd0gFHEDN51rofqxxQv5H3SavNyG6cYx/GSy5QjIPKknZUxD3quvbzWhJbvdvMEw/Onx/3UMeSc1zwNNP+gXkjYdgSIP5H8JTfsSTCUwN484vDG2RwSrtt7jlgiWbV+oYSoT9utkJP8Ol+ZFufzWc4bjXA/FnFUx7P/++mv0/NovonGSOep0e9YjMLX24ezn9lyBiJgucHPgQbpzdt5jR9RNgH3/32K2BUF5Oow07E4nUhjF76b8wvbZFvuxT7B+26CZTmCcq5K/ZCvEJUnLja/nDtDfxfnkNrrDtCtyM7C1Qsgs4ihV4hnm+RdIMZWBL4GTiIg6DvjuDkst4WvFfNgAZMmts/5OtfqgZ0ClMVDIRgK2j8UkLnMBF3ZpIyk8ECWcDN7xsZKtGgiDkELXOsTok2dWKDpYEFQFmE1Rr7V7ej9gOPbndUSKp19jgUGgKIeqFXZsBUaarIIEzU5A8Xbel09j1NGeTBvv
    client-secret: AgBaz/Xfmk/ObVjKfi0be1LYuvaGCfo/tto4qYP6BL5hgwhas7nIC67RUifMvfrh1yWQGCwEB9iB1bT5HnCkSXeyh49Sgr5ZFe67M23Soz9NXLcSEaU3MplLkZLQzRIg7TRpA+qsq8aCRobkbVpqgw8q4Q+YFl+vFDANfzQUyEgpJV2svv+32aUjCfbWrtGQwIGv4X8ykYBJIIg0vW0vV+a93KvaCTzsZDpIsY0ykR3TvPTSE2JGORjR2+Vfhxh4tQdg5tiGUDZmcaH/TY+1iVNlSm+ARgknjRcEDHtT1lN+rn4dXvSW7EqB34AxYdHgdCbMZZnzLOX3NSJVcGOOVSOHGjWHEN0ko/OV3G+dHDHDr403JC2zeaEIwBdaAvWoC/g6Nmyd+/L3sr1rCHgvV6LIE+eda/VmBOmg01/7vreU4Fsa9GjrJzf8+2R4YqqPndWj67n237hc2RGhKaW648axfJoXmjbebmkiIHzNOV0yZGo+MOTeDGyHCpIxqUXQ23A4CWull1nSxzISI7I1PmQg7syxoWuwNYmrXAM5vXeJj9dQZqgeS/ugMdWztJQRleGelhOYEWB8LnJCpg6EQYG71Dr+/Evx50b/v5DzOMpbcoxXIXQK0k8TmeRBDFx6XUwDZhgFJEDQbuJR//41T4pzXEsIFAswnsOHXuCEvxr/+T/M+ZAYyiNIluMJln10OqdcjgY6+rTveYzHN209FcQsIDhu7DxHQTCc4t9oiywIcw==
    issuer: AgAM/I9cYKmfyzAlz3vs6720LBzKkOxooF58y6quxg6dQOl+rDQ1bgOZR3fBSzDQ8LGGUmYPxAuDlpB1AtPjUeD190hKQoSFPEl1/MKP+mT/714cSe1wroB6FPhrgex0gL8n/pDizFve3fQS1s3FdRb1Ui91vF1GG3I7GgVdo5vFs+iUkvbBF9CZIE42qn2gDJeiqaEBtkrPjkaoUC6jcxYkhAGcNsflJhtelrpDGjUCRw+tdT6I1CUYzBkEpeCqkdXDa6Uj5CQCp5GQ05qL8ICThi/SFMZdL7fgQUoqD0HvNZ5GS8yAy1K13mp3Bp0ts9YH3mZ25/dNnYmNrp27CikldFg0kS9hw+cLywV60YgVnw3NPZXQ9X9tIZSJ2yIUmg8EAVW+16J8ZgX+J8dXvdvNVN69SBjpM9adPxm9cdnvX+hBfqIloOT1GMXHKnv4CFwVWZx0GhrtBNqTCrYrZHh5heAx1YevZ85yLz8VEMDMITp+n2540/JCCy1U3thxZbH4cOLG2GQrpe3yRvU8wxNorKzLkiY6m2uvBs5ArZ6S0+Rv1gxI9IqIlgbie0yah28ZMw2zon2VYev4L5i99wsSOwfFtDFA74lE4ht0k721EXOPkzkzT+Zl+gy3/jmvuNiT8Xdhv2oHfLRSwy7R50kDY++As25SKQ607J26dj4QloYIk8Woy/uRrknkatecGz2JiRlkz16CJplnR4tCRWlEIrSuog==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana-sso
      namespace: dex
    type: Opaque
