---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: nautobot-sso
  namespace: dex
spec:
  encryptedData:
    client-id: AgBX+dBvKg5QSoKSEgDeB/onuFoW/D20pUI2EeSIrdTJcjk/qjUU35Tv7NVFkTmOc5mftczVAOie8PXVSbPkche4vzyCiivVqpFh7Esrz7xPFcBZflrP/Qp+uRwr1HI9XjkbhxVZGgmLju8Zhoy2ngVcTusexM/9CoMCkw00IzICKuHTCQ5GH4YG8VEbx7sqAPznEF1DnofDQD0na+Q6i9Xe7YkRCy80PfjL9SnmckblcHuNFdyIBqOsbOAJ/e0e9rT5RkJ1sdK7RZYAjTZphLMEJj72237eLeYEuYqjm531kO09Y81xuQ+/NqR2W0NcsBdkfqdyPGH+cmjKvy6rbR4Ux32GMwAMibJ3gDSTCicLNx1FZ1YzofePJF91gzHDu3vijA5nkD+mBi1GB0xl3piiE7Z7YlaVUrM4rM/pfWdKhAthmEZ31fWV39oHyTi9ICRPTDZ5ojPkv8x4GSIpXNZ538oD0L0RtmfLPitrBlt80DUoiH2OXcYSOedn5aW8eKXhn7QZGfr+BuIa+USjweOHXPob/imqKYaj1N4vMfLv1yUBuf3RK+goVPrFB+FC6YQWkOqdtvldz5PgzaWUdmhRJhsmoH5g2K+R6soTReN505zDTZdIvA8ModQ+PvBTLZyvxPhXwAwUtkE4U5cgmo7xB/wW+5KnZeiROHbC87/035dkSSv9MvCoJCKHL9B6MBZDLwuzOHHVJw==
    client-secret: AgAeIbKF0hul6qq5Q/oekPH27p3ivVn4wWA3DLsaezHB6ieCMF1rAsgAOyJIDGsZ+9K8WMHxVbcDIM2i2vu+1QDkFRRKbV4hkHcrupIfUZraEV9SxbIC2VcKCE/Qbu0B5RlSwC0sZtcvHPIlDmJMgh9WDtT/Ubw0jlkJH6V8eKPKV+3puPfIlXM+Qb763AD4nbAPECQPM3X7AJJSlCumpLX2lh8/CV3fxf4sjweuhpE5XQFClvZ6HQ1pBTVdpKFj/uiDtNvuYHj9lk69jKbyxXS9ZzJ5FAw1fUu7HlskUXAbjt0WfVIdjd/zpTJRgMvb5gclQxZrQPGDE4LzYaabTEkgG0wT8cfoCoqNiye3GHm71HTu/iwZdXVTzOUcoICdO4SFJiSNOXDJsAUlCZCSBIT0YE0aEyYU18cmIC3DdSFSzZpVc6jetHWQ+vsvo+Iti1O/hJ0LM2ZoxwyJeRO6d5ZAKVx2OjwrZiEUsObhprP1+D/H+a3jchV6/luX0lAWTQnCcS07CjgP5YMb6sa9k0FjCzE41O5ez2TPOXBAAGylJhN5/qhoeV/6FSKp42o/8TRyqRmN9T9Uk0NLl2/f3YMXbeNT3qOFQJTVDbAvTuC8PnlUOfkOuYZzFmjSncaQGanctweno3uWNSF0jbv2YI5jzvMq3xKYmzlIfsU1E36GhrHAvhobqkgS8m9HEoDgzLqfWgIOiG8uJY6GM0TmPCVVfN2+Nrxup8XDWvRgI9tW/A==
    issuer: AgBHOIckD+R7Y62GDoJZyqR6Y8bEe5vlEj61lWWLX/DzccChP51yhHzNkXuD8KG6HSyS1UKnii9BbFh7pXVE2nQ+TucV1cGuJZlZb+dmLkOl2atypLb3YYPfvfHAPuw3bFWHGl01MYfZO/1N/m9jCeNPDw9Xh61152uE7dlnOUuvHU/UFxo9GYUqv/TzlE/iYarIY3L13wHpB/07B2uiYVr03WGVZgkeiI3pLkpMoKU7/fiVrBdv2j1MfJBt7gvq+vnTV6RJw62K54NHLFtt7ZbZVASnmGN0a2odcG3CsBF0SRPY8Lxt5/+JPrTG4gmae3byi/Vvd/bpdNhiW5qz6KQPdGZY6BIb1W/80Ky22ZoJsM+U9e2BJerTK4OqbWyKJeQHmHzmhwzmzB8PoJFMDIkYSRTnDTRgZEg+GAlA2wXyJ7INOiSj1Jsxmoegt35av6pKEX1yxzuu8wGCnHBig0S5DK9rxZ3ZdL/mcshGAU9PYUaUb6NXNKoSi01SCmqWupV24dka29L8GI7kNGQhoakoZwvBadnQucMATueFsQCHpWOc5OVxXr5gDQ6vRXxh3r7UOOqNGBtgBQommCm/Ac4lrnxMWYWpQg9td3tA74JGevO+MmgRRGiOUYeMnnKdXLGmtwF+6IU6cTYnuIRGrMvA7Lr70SN8W04nsZjiJHOZQr1qsB9RjEBntWbTcSOw1mDUfi7OiLwA82lQAeHknF7Q1zdYeQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: nautobot-sso
      namespace: dex
    type: Opaque
