---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: argocd-sso
  namespace: dex
spec:
  encryptedData:
    client-id: AgDRTsJvuFGX5VZ+Ie8BghzKB7Gkz2fYBKlbriCvcn7qcrMVhqUsmV/fU0fRWJMB4W3836+kz/bKJW1gQegYr9fc3ut7cppVWJNT1GPccIGjIJ9/fvLapKbqM00/0yQB1JaXzd8MA3QVTXrTAK2nQuCkv2HQ0aegwEn1GY+2eKpObiIO6psJb26n1zlyml2e8GfJQ2AB2GHgXHj7rOnxhkiBUjD4O1bE6u1AHJRqPrX6Lcx9isVFBoP+VYTR6zojje49oTMgQP+39d5EGw/LMnHRu0fx+/tK7d8TXl3BPKfdzk30+u98Rhu5eLdzwpAHa28vkZJOCwSggwrsJQmdFrmMzYQ4dQ5UgWpBjFSm7o3IZ0Oqoptdoghp2Gc2oyYPQqAxVsl1HNpgaRu+dvZY8XTPb+3gkm8ilt7C2UwVXSVrdE2LXAPb/IqevEpON2xzDSToLZT4p15bDn6tt11xErNlwSxnn6H0QYuAOoOwq5xt296ksSkzqo4vfF2cnZkaNsjgbGZam50fWkRbpZIEhFHFAvGjgMO0gVR0yTYShkRRn1lHEnnVEFrSzySHbXeW1dutWwFXg5qkjWnWzcpBjjFPpjQv9pd8a4K+kQ/F60KT/YgOZ2LECr5zrCjhixIJd5O3wrivzUxqD4YPYnhmMD1GqOVL71XjdH0HC8k2q7Gjwfw//dItTx+VR0oBt0aFtRJMoqn6g1g=
    client-secret: AgB4MW9vGJFOXh1r8ykhAT+Or+xFdX5lyXBA6sP+30/OLnkDaOHVGIQixHG7i+qp8XUvw+/cGbuABHnWstDY6ddHDIljyrOwCVqMkro1RCUZXoMdlpEImU9o7CGUh6K/u6rbAnUm2ciYuIDvtfbKEMOF4TMuzygK3mC/2ZZkDLPUdhznpIkR+aCSSWXz0G7xQUgShv0C8i3KifbsA7Q8B3pyo2UWMBN4dzHk+Rfmqx8QEy0THJGxgE+/yNl9fdIzrUQYehaf5erz2CBBwS3gCEFn7V4tN2OCBL3Wd8U+AiuGjAcz6JoLn1ER6B8N3BzGNoChJgjkzIXVi4LUW2OB2JEARBo6/XpWoKfTEzGLa1utmlhFY6+m4Z2rq+yFYwg/wy1bDNe6gu/y3RGQlEO2Lq99XNW5BvTNXrvwTke1nox/J+YgB9Qrj0zYBGLBu57LrcUPFMpBhn71quqHf8OJaPvWHaEh0NDc6YzZqMgqZ2FC12KjAca7TscOCw25rHGa1/ERj3y1SOA09Jz27oYrGInwNIIKQED7IwqgquUkUqqmJrUDgFV948MwMKgVi7cNjYTmD7MggeXj/+EsbYZa/iFwNcQ9bdydjC5HiugTSxkJ/1ArGtKCXnresdnQoclM4//HPtnCDEs6cJhztu3r3keZCZcm/vRivgt57S9eQTluQUIedDXtxC7Iz553RCW9QeJzqXNoN/HFrYlHvnkE4eEuOPPPHXSeK1D06y0GcvYIHw==
    issuer: AgB0NFWRI+nndIwelY26VB3XbviYJLOdwn+Gttwo/LT9ROSsjZAe1UIMPW5pSNKB98G94te4uS8QvHHrOIgXia3dAokn0mz2+7C9JOLQwpcTsA3P+wjuPAMJhdRaCBXaURL0vxcHoSs9U6Gq6pMUhAEWG5XP3Oa1sYHaMJVmNTgHiSy1vCEivUbdMz8sJ+FepKViOB1Ap+JMhRHT28Q/gtK88BAV8GKXNrl1Gjsg0xSGP9yRFNZ8a0O/jOQv53YhNZU/UL5ekZVBFa1oRSczF7lPmLGRd8kDLGiihjCkcRVOTvEnROzaN9eg+rGb/AcTfpNEU/+hA329un2aAiNswCjLGfzS/90XcenHTzTmdb/QODGDUZV2+5ruIJo1PTn+wor2/wi+clBrB0CwvUqcVStMwzSiGJTn94OyyafIvpWWoXfqZ9UPuBAeB414J+tHp2ErFPyKPksDkiV5g/rJkV561Uz4njSGINJcg8tuubjTfxwWZ9CNjwrwhGYkj+NNuSEUH3TVUwFdPXDAOfwwL3hhIRrZI5jAQddHFDos88XXLh2zS6FI4wYSsQPhjLdPCI360OwuRKrcgZs+aMhzacvxRWggLO3tjwXpelY5oHk5c554XUxt3U7cnZmFYwiM5iRwZbX7E2TCQZttT40um+Tv1tDubb92YkozrcKicU/BzE5CqDaTJu73ickZUiHaO5eDVIAqIdntsg44opk4C2emkkQatw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: argocd-sso
      namespace: dex
    type: Opaque
