---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: skyline-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgAJXt1AJGoO95TNmtqxLT3WTNgj7BVWIJTYEfA9Lg5HIdvr+jhNAjITFK8s+wlfj07fapi+na2kuKtrVNwYUfXag5RBG8BwCnj5GBqdjlueSzpC7rJCgPPXGnQAdVXn29QXIteg2GgEuaUTCcoJrkjepYr0rnch7O7hhbhlsecyocCbaZGRqYWlBK+ObS/UWB1/hJQhMXTQ+jcZ93sTzEtPiMoYntdJ5KNvFLO8fHF+meiVmbxCh4T7mZdzCWGkWyXTeXgFFUNqA+R47YjLIewZD39dSCN4jREWzHiY0Pm2KVCks2Wby45DU9Su26brI/g1i1B6kA+SPzmCDCFcxnAvGrUU/7Q/0BUHFs43XeRilTaqvIK/VEoGXF0QxtGlkjqew8Hs1P12j0AG7Vlimk2FYVNzqnZPVe4RYWHR8XVgjr/iLjMhwWtvCcgzT6dXmXHPjcBjvwyKphsFiL9CGM2ejyVQzYCG++SUYiGGIHeE7d01EfCJS1dFEkpkBN2UHxkB/oNlmPSGgRi9t+dLzkFPJUmhK2/kv+Z/YB1tBPKqszjhjOnAKOIuJBUdZ+qMRRWZzzJAk0lxilcuAlwfpzGs8jNd3Y7FWLB8Q0tyK7ErIMjO5vOlqsX8afEwS0fwvAJpEpZqzjlBh/aBeuWNAFYVmAnuiJLM+rIGR6yOnQlUtcbQihlN/iiamt3ppeMbWT35W1F9IEWgCgUJsVw8doSZqZGZwUXQfFKgrK7eyefg/A==
    username: AgAH+WZIF8Q+Qc4S/K7rmySFLhZiSJIPROFoGgXHrIaUFzG6DxnnIhE378wKBIwbb5XAKnR7HE7lB65xsubOp03SByOhOptVoTs2zuSox18KKygr6zgNim05HkLQa0hJzqoQmBJgMyW+LHN+c7Q3BdDohXEbdwzdh+J45pRE579d0UIkyt+FUujIBq+d+RcVNk318ozb596gGB/G4oCyi2hcX+WootlTZwGUYdf8YX7dvmI/8C4j95r8YamIfpioYIuJwzFtKps4qlgel0KRu72pL8MNEhrUToLasdpO7SwZvtK1Yf5HQmHs5DqlmNIjfOytvKUUzAMyw1ZOAZ+mBo2Zh3awvAQQLcWD35nAWNgGarD7xfz3BWcUr4btzGV7bGFSKmA6YSjdcFDmyWpWx88kY+8UF6hF+O9bKVGi+2cMmp/NizsaRDW8tx2sCMfC6yGKt4dPDuw5f+E23bSJPztkngSKIXxtT+HH/YtpBg4tI4xSeiXVyHIr6Ivh5UxUIatIcTc/brb1RHFItDLAvvLr5/HemHLPfbL1g8g/A78+xWGSBsvT0UjjJXWVcLJSPbJvEjorPXwA6XaMHsDb4+BButfPiZzm7C/kMzwmUWBgn6JffN6z8LdRdFvh4z+1KDGlsMTTXVZKlWkeNk/99bYUMOqnC78BoLEWMNPDOGk+WBUN9lbzmt8YHTgg+oDWBsawL7DBHIvU
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: skyline-db-password
      namespace: openstack
    type: Opaque
