---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: skyline-keystone-password
  namespace: openstack
spec:
  encryptedData:
    password: AgBtMHd1LUZZDsVGXNBQ2zhXMsky2MP8a/RTiSuXEg1wn31/SmrwRF4sxVMX7p3/qDuDK1n82BPYJoHc2HRJrFZ02XtrOkj7PvK49C2Drwr/iE5pwEzr1sfrl5oZ4+97jHwDolFrQnVZsXH3gW39cAnbmpAghqa0s7YHdiT8VrzV4f3ceXKqCeeZ7IQX4FXL5PP1XayouRdtaz878C6Jupqb/2hFfnsAdO3xRzZ1sGex6O00eTzMEDI8ipEqEvA6oZJJDJDLlRY1lOyXFb/Pg7t6Jea4wWbn77Gc1I0NhdLUIUSJiStumswIF9cUM9j3exbwYs+4tt7ezUFZ6UdFmAUeS/uvdakeFgaPY5tLLGhqn5/1pjfxuSIew9/b4OXWsuHDHfSj9lfBHazbjqq/peRFE5ejb1m5kdPAVzcE/leokDadHRVi5noCyWGed9BqLwF2gxGBF/rPZkHoUGzxmJDjF8mrrkFJHHQ+EGgHwyNLgtLyPNYCFOlupR7bVsVxIKKtJNGyVhBqd/LyLorJ1b6VBkc1hUShjX4TMhnNgNEMzIHjemZS18S676c9pnaslNlYoOTu5bIis5xSZ2IVu+rztVjpJ+a6TNoLnmrjajJE2ZiVd0KZZUTXqLix4dM90ww0Gv8U8aiWdK5uXbXLhkyXdj94AldpDUfIDXwa9u6L/gemIJEfFVpE/HIgGx/QEmfZc7sqjQhHGq0wPkRuCP+ZSzFxA2NL0qerKLDDaiEaRw==
    username: AgCW6dW9cqrr4LGlA77Ie/jLaCqHMKQaTFQr3qrKijMHo+PJ46F5++pNh080RbxJFohkcRKAHrMtUYwF2hhSb68rBvIc9Mk7r4vn8e6/EdRhTFYzkX7Orfg50RW1moYjQpvfstD8cEzgubG44xMPgvHKD3qlLv2JyQsqG0ONXByb+lw7LhEtYupWJYpoUH2SpkC2Cv1SPJpDUl+IEaVgYVV5Ps0O3AzeEmgJSMBlIvH/6dN6kzCd+axiAnmtap8FPn2trcQ4ljZ4M95R7sFv/vZexTRP6oEilZALNZepqCC7VIhRIfZUiqJhrYnroNizKC7p4fYLGs6JhGeP2tNiNONIVL7ViS1+HWpPyv1+/IGDMh+cwwSUE99gVExuXVbq5aLdxM2ZfSq0d8XD9D4r1U1STQa6BUNzJwABwUz89DmhdMRI9uEML2XabJyAaorPzZUV2ih5kkX6m9cCul0MUSKd6bQ7u/ZhEc04oKNxbQjPLEl/j1ugUrci7DQy0tKjjyzBu9q60y7lO7LsOJjWE29/RnYBQs8BtE2eUQPJWS5i78q5gV+7Uxh31hK6H1NCg2sDxuVIVO7vWosWX5D/v9crY/t7D8JoM5yBMSwaocRsevFIz+TvQ/rEMqXoVdShyeQoS8TePiUwaCTa83MNuNBxBNhf3wkKjWtBnC5cZ1cPUz87rPOCMQijIxxacK/4cVxBRFlWdhxA
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: skyline-keystone-password
      namespace: openstack
    type: Opaque
