# The purpose of this file is to serve as a template for OpenStack Helm
# based endpoints configuration so that OpenStack Helm populates the
# correct URLs in the configs that it generates for the various services
---

endpoints:
  # 'identity' endpoints are for keystone access
  identity:
    # set our public facing URL
    host_fqdn_override:
      public:
        host: keystone.home.lab
  # 'oslo_cache' is the memcache layer
  oslo_cache:
    auth:
      # this is used for encrypting / protecting the memcache tokens
      memcache_secret_key: "pB5aTRAAxOLC-RkDVxzLetHopbXWXdC9oBOQQw5UhElgROy39MQJbmdq31OQT8EC"
  # 'oslo_db' is for MariaDB
  oslo_db:
    auth:
      # this is what the keystone service uses to connect to MariaDB
      keystone:
        password: "KwReI6uphvRrKgNLfp-KPi4mhjpTAFkv"
      # this is what the glance service uses to connect to MariaDB
      glance:
        password: "Cn5MsBBtFA0NITPZg0G0bbmd4lXPDSBl"
      # this is what the ironic service uses to connect to MariaDB
      ironic:
        password: "am_-wW_37JFGR7QIULUGGPGoEB4lFjgy"
      # this is what the neutron service uses to connect to MariaDB
      neutron:
        password: "7ISNtWgnbMtxzE6Emez_f4a0Fb_z99bQ"
      # this is what the nova service uses to connect to MariaDB
      nova:
        password: "GQW8XXu60LCG46g0tVLhYV192jjSKfGd"
      # this is what the placement service uses to connect to MariaDB
      placement:
        password: "UFHSzrzTQuzn7eUwXASbvWfWMAJrE8Ss"
      # this is what the horizon dashboard service uses to connect to MariaDB
      horizon:
        password: "iAh-nwREUiQzGkTu5QCwNITutlBH4guU"
      # this is what the cinder service uses to connect to MariaDB
      cinder:
        password: "MivYprq-3IvHR6SK3qE0KmjyANGKajir"
      # this is what the octavia service uses to connect to MariaDB
      octavia:
        password: "IprUtPQvnQkz6ut2EPsZbixpnFdcCR7g"
  # 'oslo_db_api' is for MariaDB specific for nova
  oslo_db_api:
    auth:
      nova:
        password: "GQW8XXu60LCG46g0tVLhYV192jjSKfGd"
  # 'oslo_db_cell0' is for MariaDB specific for nova
  oslo_db_cell0:
    auth:
      nova:
        password: "GQW8XXu60LCG46g0tVLhYV192jjSKfGd"
  # 'oslo_messaging' is for RabbitMQ
  oslo_messaging:
    auth:
      # this is what the keystone service uses to connect to RabbitMQ
      keystone:
        password: "NMhruxqi_T4QZk3N0Y6Ki1bR_u0nWrgY"
      # this is what the glance service uses to connect to RabbitMQ
      glance:
        password: "Uz3G9Kgu0x-HxIZJpuro4bLBA4_g-SUY"
      # this is what the ironic service uses to connect to RabbitMQ
      ironic:
        password: "vhtiF_hjVyFmV1D45g_3bNELg3_JCJqO"
      # this is what the neutron service uses to connect to RabbitMQ
      neutron:
        password: "JDi4Ji7lWGtAl8mFBmTOMB1UYpzmKl_3"
      # this is what the nova service uses to connect to RabbitMQ
      nova:
        password: "UGx2r70DJJWCzukbnbTbRWALmjAesKyK"
      # this is what the cinder service uses to connect to RabbitMQ
      cinder:
        password: "eCFUtZKQfIwEKHHp1w6_XcLWdZzTugas"
      # this is what the octavia service uses to connect to RabbitMQ
      octavia:
        password: "mZV5yR9teuUKy_otXsPN4O0pF-5NqXE4"
  # 'baremetal' is the ironic service
  baremetal:
    # set our public facing URL
    host_fqdn_override:
      public:
        host: ironic.home.lab
  # 'image' is the glance service
  image:
    # set our public facing URL
    host_fqdn_override:
      public:
        host: glance.home.lab
  # 'network' is the neutron service
  network:
    # set our public facing URL
    host_fqdn_override:
      public:
        host: neutron.home.lab
  # 'compute' is the nova service
  compute:
    # set our public facing URL
    host_fqdn_override:
      public:
        host: nova.home.lab
  # 'placement' is the nova service
  placement:
    # set our public facing URL
    host_fqdn_override:
      public:
        host: placement.home.lab
  # 'dashboard' is the horizon service
  dashboard:
    # set our public facing URL
    host_fqdn_override:
      public:
        host: horizon.home.lab
  # 'volumev3' is the cinder service
  volumev3:
    # set our public facing URL
    host_fqdn_override:
      public:
        host: cinder.home.lab
  # 'octavia' is the load balancer service
  load_balancer:
    # set our public facing URL
    host_fqdn_override:
      public:
        host: octavia.home.lab
