apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret-nautobot-custom-env.yaml
- secret-nautobot-django.yaml
- secret-nautobot-redis.yaml
- secret-nautobot-superuser.yaml
