---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: nautobot-redis
  namespace: nautobot
spec:
  encryptedData:
    NAUTOBOT_REDIS_PASSWORD: AgC24WfMPm7PCE8XmKzD9Fq3FqUxe/cYB3LiTGdXFyp+DmjsRCq2hxBExivibrYRpRn7fr8YzjFnFJIgeNuA4WZtNN4hSD5vizng3vMlglFnaOb1YRrHXSw1jD047l4hQT+NizBEw4k6XOuHqj/ZI1gZTeb9Aq/3mrRdGxFmmD5DxZS0mjHcOROW+PySG3nrhZPrIUUvwgkBlT8VwvlUrV9bGpCH7gFtjnkzzEHW7LK4fe8m2kKFf0xsQmW5geEkRtK9JItVmMz8AoUrWz0nCMkpFezWnOpzC+Bsye8Amr0llAOBS+Z5PseGXmFBiB4sjYbOmp4ztxmIP7E3RrYB4g96mroTJCzvpYio72E835SIlErAr9NNwExXuYqqHbchePyr2F4erC6JKE8sLygbNcdu2nzGeN2i57lPbc1HGUC3OU6B3/typdIif78NdDXSI9JUaVu7SpS8A630rcpmQG0Q+erFYD9y+vYGEfVOcJg3a0rvjaqeXj3uUgLuhp+k2JCc8H9qYwdln00118JeSTe2q+lifyv9XKgeeB1dQLaAsD/M6haAS11xe7Pw9eWS50pkQuO/y5ESvCaYv/Mb/jzTe5p6sPc0xTTYo4nUsJ+Hz+sSu5hTohgQceKwVIDzGlEQhko8uTtiDOGJ1drwjB3mFqQtFPW9D7XDKT9bwfJ2y05m0JYFiMsCLRlnoxSgI0iJvuybxg28600GZJ7uDKkMwWWPl2/EcZCHjQJH6E2m6A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: nautobot-redis
      namespace: nautobot
    type: Opaque
