---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: nautobot-django
  namespace: nautobot
spec:
  encryptedData:
    NAUTOBOT_SECRET_KEY: AgAqHlIcgfxMFR1++Hskilnxgd5Pj8zfMKpmZoTRDW43BqGy2Wl42e+xvpIBsRQSD1d+/kVc3vMY/YirFQVmEe0BmMwokxtN9ZsENKP4Q+Xy4ydn0Om/acSrtgYprtcWRx5+6NaGH1qM5YtgPIfEHEuVfT+uPH5c7bRyF5wBpxCbh3gAPeP1Jl9+RbRC17UbA+58Ozixt2qu1kz7wTVRrMI0r2NIPEQquphsjsEUUwqpDKJr/JJk0WTSyUgD8B6rUnJ+YJeIDIEM/fk6vGf/mmCl35ETr36AlrN1pJt3jq+WF82yyYKP/upGjQdQDoHFe+7isvWkakJ3Cp2bpXWOfUGwjID3Pbt/OTVRNE1zl3yAU01ccDef4FRGoF7lqtFJCzUtVDCci6AFVlw6agKhQA+P+0wtsqvH3umsI/R9yn/mszMcvgUTv8XKuRminRv8UW7RHIrf/Cqc5F8dDNcvewUpVWWIV2AqylEat9Su2e0qUliTgfl80E2Ee67wCEyX6MIjMiU9/uCL1Of7kVLG5vhSXZY++kljuFenGwrFxkAdP5i4ELW5DeZuPsQ/mLd1j2MnAWxCxZw12cWphtOFYryG9ObFyHcS2CCxaaG+/hXVka2SLrC5qS7yl1oVOJBc0a6YYNxKF1+hnuF4181fYEGEjT+AX8+JBQKfMfPWBneHTaKVgxgOY7JQKCxBG19KGAjiTN0bM+QyqHdlhGS2u8uy0i90SwXlB/zzpKDZ89fw7A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: nautobot-django
      namespace: nautobot
    type: Opaque
