---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sso-passphrase
  namespace: openstack
spec:
  encryptedData:
    password: AgCQ0C6UGJ7d9VDImO18ROreFV3kvAizLDlxYSb8VmvwYNa40TjNw2MX2DHERCYwPDzktuNovXPrjMtSFg2rdBU4z2/gt65zTCShkkKNKRXG5aB9fyei6lsv24x6HObMJ2piimyVqBA9U3vw7hNXZfQlKnTsmp63GX67j9G2NlQeMlUWy6EBhZx5zlFr3Xt57HEnN0tw3fBFThwnpVVVmjhjF8Ti2e4JEAOhDiFtZdC7GDB5Lps8KWI0AAQODwm1Sl0eYq/BR3pJG7PX+8olJFHDCfQyIKP03EheELTTGSLIQ3kxV9Vv9FoUbIbSDfwhU6MzwyMC/M9lYdWsjxGgpylGWuyODRZp8vi9HaEeFxeUO2wcgUhIG4oOMdbBE8DLkhmALzQ6gqJEFfeRGwFhLW+bK5vh2G0E+h8xxnSfhx0EGbhhFc7+sJL4tG2FO0lXYDjmyc9S57dGOb5Kp5D7QWhK9Sek6h2bhv07tww39X/ol0JnZ+o9pey5WUUrgf5Zm/pi20jI9DSRvbbCzbigLy/XIX5O39hw2OxRCEBb55Aa9523TnbK+ND5tStv7+50xzNfY7EXXSt3U7HtAZhpKGfGAiTRQOXFXwJ2GCi/6JVML5xoWWZSOONECz2VvwvmG6dS8XZ7z/r8rqkI6XP2kuobli43Kcens11fAfXKOz+bQ3D4lxVGWtpm3ulpXpvfZyBaWC3r2UHDydghzbjhMgdJu5rShX5ma7h+/lWfA0NoIw==
    username: AgAgKXwGaCi1zp5pe1MmOemHru3Q0TEMqslrgQ9P8ZmOnNtswK0VhetEV93yEaw492wg4nFG/g7ka6azXiN4KGNJ8dsByNaISakkctiI9+HYTr2aiRd8zUdlixWXRf/qfhBXP3mwwAa8JpV8Y6unmFLD6MXfkCj1s59g+zUc5NTpurRHywPXxUl1y5YgwHC+JGmk+XKxLsoTeTfymPyEVJwzJLOrNa3o0wd7PrII1ofIqy8qyZwfQMZcU6YgCz41UaJcQ1ozVLiUPi6n9Tu307obZU/trdehlTqscYeybLuzx6tb4fud+s0104+zYqq1Au4aCbW5HPAc3vnT9FIpsS7ZY4ARubKLafCK9Y+co4kjm/4pp0mh+feMoO3cLPMO59/jG7eZHGSA/BDMhX30iqsR5zwv515++53sGK97/6le1Cgo+nabUbRtK7M9PyFKEgZlrRYKzC2Fl7HIasUYMBGEqdwEnyug3SI4beC8B7FH3mqqtx37y82M+0CFW7bDhwyTxPv6gMFowDOsC3P+flA3kJ9nzDdtbCWVTOBVtgBSwq+FWyV9ccV3QqYSI1lPFYibFnNeKQPVWEV9eAAxuZLXxOG5D9zjrdaJ5Crp9xbJR0Gm7kzg9PpQ00xBcepOswC9/75AR/VoYteby3guDcoYqRMdG7wvrhRj5xt1C/cK9cDpZ5htrl6gePyih0xfCkU7ecNmPzEWJOjP
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sso-passphrase
      namespace: openstack
    type: Opaque
