---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: admin-keystone-password
  namespace: openstack
spec:
  encryptedData:
    password: AgBGRhvkMA2uwkH7eoSSaqrMhpfon1EED8n7898zuji/rH8kYwJhK+0DifKJEhJmnW+TSNkZk4wI9TDuvvjHUdAaSGwUmj5WJMDjf22SoNqIGz08rwuIo0y/LcKzfB/gaFXy8Sgynym4PQkdvAC0Vf9MYEIRC56pa4YQ7wAKD1Gbh2zUJd0kLPjHSLtWcI+3hCBfUVSEK1gtXZWiz/PRbw7OmPQGfz98cwqJxngjaUzzajf8bZt10MQeHhQhVMwzpevgko3yd0bBpJIWBTGqildbRkmmmrPbOsS55eaR7tUBY1Te7h6KnkDiyTaiMyJbp110tAGEe/K781mF1Z+fYMjzoUsbrUt6qf8bGmEQsPnM9kZ9+dDKjQHgCEplywGEadNHdSmhfQm7lSxyrgvlha1R0KycCiaePis2LZ+HpZ3YCRrJ354FHqlZpVC1hlHLAxtbHgdVnAntJeLPgAjLSXdJP5iJ/SaeiZVfD7LFdX3oiDukBOYAhGCAHvY0v7TrquZyeG01G486vWM48yEcyO0UT/E7Ybr2tavCG7dn1vtbdVmGaDj2F+8UuyKF6/DIt92sIpk+cea7cq0nq7I5/ri5K7gK/11hUzoe9WmG7jKgAbTjYImzSRyFeO4uqVVZ04Og/TGRB7uC8Hgn8owqePWtsER3n6gcSI50PtAOeg9GqyZViW/bfGuESkuENKVUyB24liKs5VGioxuhOLMMXAKu1zx6hZnk50p5ztYea28Xjg==
    username: AgC+oW/0w9oxqdc9h7gppnMHgHQLxc+ysE/TIKt3BBXDT5vBNYPTRPq3HFBamxPZg0WHC2duHpkyFAMW33/NTtdYS1enYHqB56vW28xnaPvP/8VX5KPXQJTk5nTXqaqIYgwSQ9EqfzH81a8MZrHu0xYj2vQX/caH/6rQBBXbf2wPWosQ1A+P/sYq/hTXEAodHwsJsAob4G/AyrODOw8nCBnYmYnELKXEisPtqmcAOBzRRQhXBHCMOoNYneUMJMFy7nqOjhxL939/MzosOpIKy4B/JAnlzPDDr0zxMkNesvTjTMpppTwO4xRJ3CEMctcSGMX8ef3kSvAny7XR+uvOC64aaynrM057IvOdYZOzDkYGiYzOYhMtbI3mXIQB3whoOZAROxAaaVMQrrBI+nrwWg5GUfYWa6wJVMoFXAXGZdcvImVvvZkquGdAL/09Rn9+Wqb2eYrkx80CFUiyd8DcTvbR8b1b5zTGzlVRubxoiwHHgrZQQfKMeJCcL8t5sLZUy5L3J/oguGhhL2YZjteZ+XhfikkKYdmWGUiX1EXxu8tllnqsvNcmUjnwCB2tZGJnqTnTu0S7i3rikyp3/WkRLDSm1LWiGXEzFsOPauEPqkX8eUONK9iUFBnXn7POTb9+MLsAuF2jsb5vODN6uX03XCrR54eAso8aMd/jq7tDylAsB7aJ52NGtykt0mde5S+aJ4PVyRoJSA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: admin-keystone-password
      namespace: openstack
    type: Opaque
