---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgCu2Smw44gLCHgj2IlRUNsG/bj8Gn1oJY7Lgl1PCfwdmmgt9BVaIsu1StXNm8Ldm7SKXXrd4ZVkQLJSK3sqRhE1RUJuAzWvBd7lwE6qtdXlcYsyfvgk8vd6SP5ebUnymRQrYGuGzdNe6tqHgYw83cJW5zceZ3FwNIX52+KakRm3cQzUIIhJ9N8yaYDwvv2G8lSsS+SSTK5HvnaxV9j/EsuekvpQjfp7xJv0C25hZsNTjv6BX2pz2OPZvQAZOaMvJAVWGz+bOfepkM6EF1MXNyGXROiupT89de65bBy1gzmKpm1dFXW4pxXOJ9DE1NCm1JE2fEg2qRrtTISQPaACKBWSbMBbNg3ns587fy8UThAHf9jIG7BdX9oas8zagw2D0Gh7LHKVMwNFYmxN90B5AqBgtrG68+BXxw0grHYT34tkEm8S1r04X9EtC6x7V4s2FIh3Ji2zoJaPcvZ7rLjGrBS2XSQHzFpzxxiUZczbN4aSqyVynZBFZxBEKWkyUUykuD7T+UC9tMHDHWLFOXtTRraWMVvMgXHV91gHTRwnI5fnA4YhNoJF0X0WUnNnwAdO/P2L6qekT8JlrH3Hydd/2uKHEY+rOM9tqdg56AmXKWMmEZh2dcgrSJVJ0IvgXtUyGAbJgt9Th4uZrcPYvq2HZPnxi5WcMpaxHsSEni2+fjlj6CPNjOdnExkSgwwf/FSbPhDQOe02NxR0g9oA5z0nShsotcN252/XW5SeU7gibnwOAA==
    username: AgA490rsmHuvhdmahoO74p2aMjPnSGTH+Xa7EDyNtyN1I6Sqwd0X7n5xkpMU5CTGhiuGO2OL4oT2ofn8nVKSmDP9lVDOTxG3HdwAZw39p+dN7vxhcOx9GaVcjLOVdW/bEi51ULsYu2bUf1fHRw/fiReyqvziIJipZ+w/VHmEfuWDprnK7QnmDbCYFrKF46wAVbcMLCjdBqwZTzaBXXJqKaGUrOaJXDU8x/Y42ISqzBgPMEtwGCe5Kus+JuqX+yhwoRy388b95sdqgvW0WzIFI4icD4y76OMTtUef+mmVTw6h0SICVa0iAQR116faB87MtVY6djtD4qzl2iM4ac3epAWcVn9r26wzD75bLmQAqqrMLptYjlH5mIvZuJKAA5L5L5hyMOest8JjTk+zCsvzL7KrNBSmje/J2oALOkDP2+m8UgFciw0mANr94bp3VoZbUaFsjaRTGa14TaYags6r5FXtuBPgGdDEGyNb9zVPPnHMtS99rUtb6EzL2TK7qUhSl4WIC+E90y2tlRGq0XlW6RkJMO5y1ENwaYIqWqNHHPijfZuKAJ/1B0A3UzzOWnBWKbefmUFmge5+hwZCRmIUJI/p2zIS+zHKS38TfFWp4DnqPfJOx8919tXGl+cBPtkkxXGRBPuwPDRYB6hX2Nq5cN4w5vAYnGW7oESBZvcI+P12PcmvxDqKY03yOUSVET5Jr89ZdJr2X/RGow==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-db-password
      namespace: openstack
    type: Opaque
