---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-rabbitmq-password
  namespace: openstack
spec:
  encryptedData:
    password: AgBmUjPgvmQICEMES3UrnAclW80EgCigQztwvsLKszwsDk9/81V9mqDVp63v0A4iUcri7V5rGSjC6eu2sdRh50QdxYUk+q6y4OgZhNM/ZfekKJAHy/NKon5dBkFZVunxxLsNSDS0R0qo/5SVJfPp0YzeSLSiCQirfGh0Bqhd8KhqUOH7biqgoYgXwGt8IWtheyg3H9gcP+rbl6tEMeYJl2onP15C3Jno7r9Sk2NE/0Kk9Plc4OpReFeWSkUzK2BuiHQqK5w5O0+N0mLt37VB62fT6s55ClAAaaoaGOVWyMRkuD6CdMrulLlkhbOBrwjKHU1fmJlKtdR+MDwdv6gaRxFVzKutOulJf3NlUmDJbPxChxR4lgDWnafR6VpgcvBVI2nuyBCrUNvOjcb1hLalZIoFcwKCXYdqMoHANKpcuyNSp+9moxP6hBRiDevMDkpvqBh+nG7aYbqUf0YIRh9GUVua9v3vEX6XlhxKmJ/dYnuhLRrrR4WEmu0m5ogiHKysPqVFOHpnBVwI640dUeSFNNaOoD5B6rIYDNY3mQCDTwDRLS9iBBdAHbgp+cbEL3wvily+4oVrrg6SFd5zjDS8b8VU/SQDak39r0Gc6f/eDF8rhxVpTFFtQdyBb9DFv0nZLkPimWHLwkvy6o5gal2DFj4X2B6tD1gZyn1bM/2XyA7c4o98ic397movsT/pW+4uwBw9fgg/r7foF6ug2xAHBnuFOU8Rit7RHkklJhcMR0m9lQ==
    username: AgAUf4fQBqBN4RMZupy/lLiKmla/bK9cxQ9oVhG6iqUSkuqWhkK4+BEHtSQIz4FOczZ2ZdceJ/B4yzi+UrXaow8gR8DmVFl9YjFP/MZkFvPEKErcXiGitv/iwPREMeiKft73KZqkjn02Op1r7ZZldd6+YiP2u9yzTsIF6cW6an6pmQowL4zwbEJ4TQzkv26L+HUWN4rJLPcLIsWI/4kOw48XbHt35IcM1b6ftTbenLiShUeI1yuRsZYphsdAgdexUrn2NJvGi3MigV2gyt4PZMiPp//OIWBCTo2KQ6XNGJSQzsSkm75HrLDoyOdBo387JzEP9+Uv0BtcKO6R47D7XEGB0mIR80X603PmHuTxeEQeLRTzfrTj+saLJnmjNv2YmsEZpJpHyVYKGvogwq336tpjj+52LTMDmz54mIBH3DNFR8kxtdO0Vl60ClU2/tUkrMFmxo/KTDYFmibGCeMwYab+2SXWkcX9+pAidY2Ds67RKDWNt+nV94nAYF8+ZExqBZ0UVbSK0iigEAjfp8zTmH+uMhizaRr4phV9nA2p8UeWIbxxoWxZFWROJ2n1h3yv1tdZXZfHMaB55ag1OK7cQgXcoLXWYUx36Zkf31tBpS/kqS4i9CaSMO21AAhMAKUWR7gqFBRKQ78M2nrgARkxcjJs7I/rriAzv1tRtsO6ZEfbQWfc3tZZ52KeRbYSj2RUM5dHDpgyFdiXiw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-rabbitmq-password
      namespace: openstack
    type: Opaque
